# This is my attempt to clean but I didnt remove except duplicates left the rest so everyone can look at the flagged but most of the flagged was not parralized correctly aka has NaN values

In [1]:
import pandas as pd

df = pd.read_csv("/kaggle/input/datasets/feryaljadallah/3-level-parallel-samer/parallel_samer.csv")
df

,Original_Sentence,Sentence_Level1,Sentence_Level2,Sentence_Level3,Novel,Chapter,L4,L3,Line,Source
0,الفصل الثاني,الفصل التاني,NaN,NaN,0,2.0,الفصل الثاني,الفصل الثاني,0,SAMER
1,«وكان صباح..,كان يوم جميل.,كان يوماً جميلاً.,NaN,0,2.0,«وكان صباح..,«وكان صباح..,1,SAMER
2,يوما واحدا»,يوم واحد,يوما واحدا.,يوماً واحداً.,0,2.0,يوما واحدا»,يوما واحدا»,1,SAMER
3,قضى فتانا إبراهيم — وهذا اسمه — ليلة هادئة عمي...,إبراهيم قضى ليلة نوم عميق وهادئة، ما عدا حلم ق...,قضى إبراهيم، وهو اسم الفتى، ليلة هادئة ونال قس...,قضى إبراهيم، هذا هو اسمه، ليلة هادئة عميقة الن...,0,2.0,قضى فتانا إبراهيم — وهذا اسمه — ليلة هادئة عمي...,قضى فتانا إبراهيم — وهذا اسمه — ليلة هادئة عمي...,2,SAMER
4,ينحدر على أحد جانبيه نهر جائش،,ينحدر نهرٌ على جانب هذا المكان.,ينحدر نهرٌ على أحد جانبيه.,ينحدر نهرٌ على أحد جانبيه.,0,2.0,ينحدر على أحد جانبيه نهر هائج،,ينحدر على أحد جانبيه نهر هائج،,2,SAMER
...,...,...,...,...,...,...,...,...,...,...
20598,ليته يدري!,ليته يعرف!,ليته يعرف!,ليتَهُ يَدري.,9,8.2,ليته يدري!,ليته يدري!,27,SAMER
20599,إذن لهدأ وجيب قلبها،,لقد هدأت وجاء قلبها.,لقد هدأت وجدبت قلبها.,لذلك هدأت وارتاحت.,9,8.2,إذن لهدأت رجفة قلبها،,إذن لهدأت رجفة قلبها،,27,SAMER
20600,واطمأنت إلى سعادة اليوم والغد.,سأكون سعيداً اليوم وغداً.,واطمئنت إلى سعادة اليوم والغد.,واطمئنت إلى سعادة اليوم والغد.,9,8.2,واطمأنت إلى سعادة اليوم والغد.,واطمأنت إلى سعادة اليوم والغد.,27,SAMER
20601,حسبها أن يذكرها جانبلاط،,جان بلاط ذكرها.,جانبلاط ذكرها.,حسبها جانبلاط تذكرها.,9,8.2,كفاها أن يذكرها جانبلاط،,كفاها أن يذكرها جانبلاط،,27,SAMER
20602,وأن تطيف بخياله وبينهما ذلك البعد البعيد!,وأن يتخيل بينهم مسافة بعيدة!,وأن يتخيل بينهما مسافة بعيدة!,وأن يتجول بخياله بينهما!,9,8.2,وأن تطيف بخياله وبينهما ذلك البعد البعيد!,وأن تأتي بخياله وبينهما ذلك البعد البعيد!,27,SAMER

In [2]:
df_clean = df[["Original_Sentence", "Sentence_Level1", "Sentence_Level2","Sentence_Level3"]]

In [3]:
df_clean = df_clean.rename(columns={
    1:"Original_Sentence",
    "Sentence_Level1": "level_1",
    "Sentence_Level2": "level_2",
    "Sentence_Level3": "level_3"
})

In [4]:
df_clean

,Original_Sentence,level_1,level_2,level_3
0,الفصل الثاني,الفصل التاني,NaN,NaN
1,«وكان صباح..,كان يوم جميل.,كان يوماً جميلاً.,NaN
2,يوما واحدا»,يوم واحد,يوما واحدا.,يوماً واحداً.
3,قضى فتانا إبراهيم — وهذا اسمه — ليلة هادئة عمي...,إبراهيم قضى ليلة نوم عميق وهادئة، ما عدا حلم ق...,قضى إبراهيم، وهو اسم الفتى، ليلة هادئة ونال قس...,قضى إبراهيم، هذا هو اسمه، ليلة هادئة عميقة الن...
4,ينحدر على أحد جانبيه نهر جائش،,ينحدر نهرٌ على جانب هذا المكان.,ينحدر نهرٌ على أحد جانبيه.,ينحدر نهرٌ على أحد جانبيه.
...,...,...,...,...
20598,ليته يدري!,ليته يعرف!,ليته يعرف!,ليتَهُ يَدري.
20599,إذن لهدأ وجيب قلبها،,لقد هدأت وجاء قلبها.,لقد هدأت وجدبت قلبها.,لذلك هدأت وارتاحت.
20600,واطمأنت إلى سعادة اليوم والغد.,سأكون سعيداً اليوم وغداً.,واطمئنت إلى سعادة اليوم والغد.,واطمئنت إلى سعادة اليوم والغد.
20601,حسبها أن يذكرها جانبلاط،,جان بلاط ذكرها.,جانبلاط ذكرها.,حسبها جانبلاط تذكرها.
20602,وأن تطيف بخياله وبينهما ذلك البعد البعيد!,وأن يتخيل بينهم مسافة بعيدة!,وأن يتخيل بينهما مسافة بعيدة!,وأن يتجول بخياله بينهما!

# Kind of cleaned the data so I can work with it

In [5]:
# Install dependencies if you haven't already
# !pip install pandas openpyxl sentence-transformers scikit-learn pyarabic transformers torch tqdm

import re
import warnings
import numpy as np
import pandas as pd
from pathlib import Path
import torch
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity as cos_sim
from transformers import AutoTokenizer, AutoModelForMaskedLM

warnings.filterwarnings("ignore")

In [6]:
import torch
print(torch.cuda.is_available())

True

In [7]:
# ─────────────────────────────────────────────────────────────────────────────
# CONSTANTS & THRESHOLDS
# ─────────────────────────────────────────────────────────────────────────────
LEVELS = ["level_1", "level_2", "level_3"]
ALL_COLS = ["Original_Sentence"] + LEVELS

# Models
SEM_MODEL  = "paraphrase-multilingual-mpnet-base-v2"   
BERT_MODEL = "aubmindlab/bert-base-arabertv2"           

# Evaluation Thresholds
SEM_SIM_THRESHOLD  = 0.70   # Below this → meaning drift warning
PERPLEXITY_CEILING = 500    # Above this → grammar concern

In [8]:
# ─────────────────────────────────────────────────────────────────────────────
# TEXT UTILS & DATA LOADING
# ─────────────────────────────────────────────────────────────────────────────
def clean_arabic(text) -> str:
    """Strip diacritics and non-Arabic chars."""
    if not isinstance(text, str):
        return ""
    try:
        import pyarabic.araby as araby
        text = araby.strip_diacritics(text)
    except ImportError:
        text = re.sub(r"[\u064B-\u065F\u0670]", "", text)
    text = re.sub(r"[^\u0600-\u06FF\s]", " ", text)
    return re.sub(r"\s+", " ", text).strip()

def tokenize(text: str) -> list:
    return clean_arabic(text).split()

def load_data(df_or_path) -> pd.DataFrame:
    """Loads data from a file path or accepts an existing DataFrame."""
    if isinstance(df_or_path, str) or isinstance(df_or_path, Path):
        fp = Path(df_or_path)
        df = pd.read_csv(fp) if fp.suffix.lower() == ".csv" else pd.read_excel(fp)
    else:
        df = df_or_path.copy()
        
    df.columns = [c.strip().lower() for c in df.columns]

    missing = [c for c in ALL_COLS if c not in df.columns]
    if missing:
        raise ValueError(f"Missing required columns: {missing}\nFound: {list(df.columns)}")

    df = df.dropna(subset=ALL_COLS, how="all").reset_index(drop=True)
    return df

In [9]:
# ─────────────────────────────────────────────────────────────────────────────
# COMPLEXITY METRICS
# ─────────────────────────────────────────────────────────────────────────────
def complexity_metrics(text) -> dict:
    words = tokenize(text)
    n = len(words)
    if n == 0:
        return dict(word_count=0, avg_word_len=0.0, unique_ratio=0.0, long_word_ratio=0.0, complexity_score=0.0)

    avg_len       = float(np.mean([len(w) for w in words]))
    unique_ratio  = len(set(words)) / n
    long_ratio    = sum(1 for w in words if len(w) > 6) / n

    score = (0.40 * avg_len / 10.0 + 0.30 * unique_ratio + 0.30 * long_ratio)

    return dict(
        word_count      = n,
        avg_word_len    = round(avg_len, 3),
        unique_ratio    = round(unique_ratio, 3),
        long_word_ratio = round(long_ratio, 3),
        complexity_score= round(score, 4),
    )

def add_complexity_metrics(df: pd.DataFrame) -> pd.DataFrame:
    for col in ALL_COLS:
        metrics_series = df[col].apply(complexity_metrics)
        for key in ["word_count", "avg_word_len", "unique_ratio", "long_word_ratio", "complexity_score"]:
            df[f"{key}__{col}"] = metrics_series.apply(lambda m: m[key])
    return df

def check_simplification_order(df: pd.DataFrame) -> pd.DataFrame:
    scores = {col: df[f"complexity_score__{col}"] for col in ALL_COLS}
    df["order_ok__orig_l1"] = scores["level_1"]  <= scores["Original_Sentence"]
    df["order_ok__l1_l2"]   = scores["level_1"]  <= scores["level_2"]
    df["order_ok__l2_l3"]   = scores["level_2"]  <= scores["level_3"]
    
    df["order_valid"] = (df["order_ok__orig_l1"] & df["order_ok__l1_l2"] & df["order_ok__l2_l3"])
    return df

In [10]:
# ─────────────────────────────────────────────────────────────────────────────
# SEMANTIC SIMILARITY (PATCHED FOR MISSING DATA)
# ─────────────────────────────────────────────────────────────────────────────
def compute_semantic_similarity(df: pd.DataFrame) -> pd.DataFrame:
    print(f"Loading semantic model: {SEM_MODEL}...")
    model = SentenceTransformer(SEM_MODEL)
    
    # Fill NaN values with empty strings and force them to be strings
    orig_texts = df["Original_Sentence"].fillna("").astype(str).tolist()
    orig_emb = model.encode(orig_texts, show_progress_bar=True, batch_size=32)

    for lvl in LEVELS:
        # Clean the level columns the same way
        lvl_texts = df[lvl].fillna("").astype(str).tolist()
        lvl_emb = model.encode(lvl_texts, show_progress_bar=True, batch_size=32)
        
        # Calculate cosine similarity
        scores = [float(cos_sim([o], [s])[0][0]) for o, s in zip(orig_emb, lvl_emb)]
        df[f"sem_sim__{lvl}"] = [round(s, 4) for s in scores]

    return df

In [11]:
# ─────────────────────────────────────────────────────────────────────────────
# GRAMMAR PROXY (AraBERT MLM)
# ─────────────────────────────────────────────────────────────────────────────
def pseudo_perplexity(text: str, tokenizer, model, max_len: int = 128) -> float:
    cleaned = clean_arabic(text)
    if not cleaned: return float("nan")

    inputs = tokenizer(cleaned, return_tensors="pt", truncation=True, max_length=max_len, padding=False)
    input_ids = inputs["input_ids"][0]
    n_tokens = len(input_ids) - 2   
    
    if n_tokens <= 0: return float("nan")

    total_log_prob = 0.0
    with torch.no_grad():
        for i in range(1, len(input_ids) - 1):   
            masked = input_ids.clone()
            masked[i] = tokenizer.mask_token_id
            logits = model(masked.unsqueeze(0)).logits
            log_probs = torch.log_softmax(logits[0, i], dim=-1)
            total_log_prob += log_probs[input_ids[i]].item()

    return float(np.exp(-total_log_prob / n_tokens))

def add_grammar_scores(df: pd.DataFrame) -> pd.DataFrame:
    print(f"Loading grammar model: {BERT_MODEL}...")
    tokenizer = AutoTokenizer.from_pretrained(BERT_MODEL)
    model = AutoModelForMaskedLM.from_pretrained(BERT_MODEL)
    model.eval()

    for col in ALL_COLS:
        print(f"Calculating perplexity for {col}...")
        df[f"perplexity__{col}"] = df[col].apply(lambda t: pseudo_perplexity(t, tokenizer, model))
        
    return df

In [12]:
# ─────────────────────────────────────────────────────────────────────────────
# CUSTOM EVALUATION FLAGS
# ─────────────────────────────────────────────────────────────────────────────
def assign_evaluation_status(df: pd.DataFrame) -> pd.DataFrame:
    statuses = []
    details = []

    for _, row in df.iterrows():
        issues = []

        # 1. Semantic drift check
        for lvl in LEVELS:
            col = f"sem_sim__{lvl}"
            if col in row and not np.isnan(row[col]) and row[col] < SEM_SIM_THRESHOLD:
                issues.append(f"Semantic Drift ({lvl})")

        # 2. Simplification Order check
        if "order_valid" in row and not row["order_valid"]:
            issues.append("Order Violation")

        # 3. Grammar check
        for col_suffix in ALL_COLS:
            col = f"perplexity__{col_suffix}"
            if col in row and not np.isnan(row[col]) and row[col] > PERPLEXITY_CEILING:
                issues.append(f"Grammar Concern ({col_suffix})")

        # Define status based on the number of issues detected
        if len(issues) == 0:
            status = "Pass"
        elif len(issues) == 1:
            status = "Moderate"
        else:
            status = "Flag" # 2 or more issues

        statuses.append(status)
        details.append(" | ".join(issues) if issues else "None")

    df["evaluation_status"] = statuses
    df["issue_details"] = details
    return df

In [13]:
# ─────────────────────────────────────────────────────────────────────────────
# MAIN EXECUTION
# ─────────────────────────────────────────────────────────────────────────────
df_raw = df_clean

# Run pipeline
print("1. Computing complexity metrics...")
df_processed = add_complexity_metrics(df_raw)
df_processed = check_simplification_order(df_processed)

print("2. Computing semantic similarity...")
df_processed = compute_semantic_similarity(df_processed)

# Toggle to False if you want to skip the slower Grammar check
RUN_GRAMMAR_CHECK = False 
if RUN_GRAMMAR_CHECK:
    print("3. Computing grammar scores...")
    df_processed = add_grammar_scores(df_processed)

print("4. Assigning evaluation status...")
final_df = assign_evaluation_status(df_processed)

# Display the requested columns to verify
display(final_df.head())

1. Computing complexity metrics...

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

2. Computing semantic similarity...
Loading semantic model: paraphrase-multilingual-mpnet-base-v2...

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/723 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.11G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

XLMRobertaModel LOAD REPORT from: sentence-transformers/paraphrase-multilingual-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/402 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Batches:   0%|          | 0/644 [00:00<?, ?it/s]

Batches:   0%|          | 0/644 [00:00<?, ?it/s]

Batches:   0%|          | 0/644 [00:00<?, ?it/s]

Batches:   0%|          | 0/644 [00:00<?, ?it/s]

4. Assigning evaluation status...

,Original_Sentence,level_1,level_2,level_3,word_count__Original_Sentence,avg_word_len__Original_Sentence,unique_ratio__Original_Sentence,long_word_ratio__Original_Sentence,complexity_score__Original_Sentence,word_count__level_1,...,complexity_score__level_3,order_ok__orig_l1,order_ok__l1_l2,order_ok__l2_l3,order_valid,sem_sim__level_1,sem_sim__level_2,sem_sim__level_3,evaluation_status,issue_details
0,الفصل الثاني,الفصل التاني,NaN,NaN,2,5.500,1.0,0.000,0.5200,2,...,0.0000,True,False,True,False,0.7551,0.3324,0.3324,Flag,Semantic Drift (level_2) | Semantic Drift (lev...
1,«وكان صباح..,كان يوم جميل.,كان يوماً جميلاً.,NaN,2,4.000,1.0,0.000,0.4600,3,...,0.0000,True,True,False,False,0.5359,0.5311,0.2447,Flag,Semantic Drift (level_1) | Semantic Drift (lev...
2,يوما واحدا»,يوم واحد,يوما واحدا.,يوماً واحداً.,2,4.500,1.0,0.000,0.4800,2,...,0.4800,True,True,True,True,0.9808,0.9842,0.9730,Pass,None
3,قضى فتانا إبراهيم — وهذا اسمه — ليلة هادئة عمي...,إبراهيم قضى ليلة نوم عميق وهادئة، ما عدا حلم ق...,قضى إبراهيم، وهو اسم الفتى، ليلة هادئة ونال قس...,قضى إبراهيم، هذا هو اسمه، ليلة هادئة عميقة الن...,23,4.130,1.0,0.087,0.4913,21,...,0.4909,True,True,True,True,0.9143,0.9612,0.9498,Pass,None
4,ينحدر على أحد جانبيه نهر جائش،,ينحدر نهرٌ على جانب هذا المكان.,ينحدر نهرٌ على أحد جانبيه.,ينحدر نهرٌ على أحد جانبيه.,6,4.167,1.0,0.000,0.4667,6,...,0.4600,True,True,True,True,0.9307,0.9491,0.9491,Pass,None

In [21]:
final_df_clean = final_df.dropna()

In [22]:
final_df_clean["evaluation_status"].value_counts()

evaluation_status
Moderate    9821
Flag        5705
Pass        4234
Name: count, dtype: int64

In [14]:
final_df["evaluation_status"].value_counts()

evaluation_status
Moderate    9903
Flag        6457
Pass        4243
Name: count, dtype: int64

In [15]:
# Filter the DataFrame to only show rows with the "Flag" status
flagged_df = final_df[final_df['evaluation_status'] == 'Flag']

# Show the first 10 flagged rows
display(flagged_df.head(10))

,Original_Sentence,level_1,level_2,level_3,word_count__Original_Sentence,avg_word_len__Original_Sentence,unique_ratio__Original_Sentence,long_word_ratio__Original_Sentence,complexity_score__Original_Sentence,word_count__level_1,...,complexity_score__level_3,order_ok__orig_l1,order_ok__l1_l2,order_ok__l2_l3,order_valid,sem_sim__level_1,sem_sim__level_2,sem_sim__level_3,evaluation_status,issue_details
0,الفصل الثاني,الفصل التاني,NaN,NaN,2,5.500,1.000,0.000,0.5200,2,...,0.0000,True,False,True,False,0.7551,0.3324,0.3324,Flag,Semantic Drift (level_2) | Semantic Drift (lev...
1,«وكان صباح..,كان يوم جميل.,كان يوماً جميلاً.,NaN,2,4.000,1.000,0.000,0.4600,3,...,0.0000,True,True,False,False,0.5359,0.5311,0.2447,Flag,Semantic Drift (level_1) | Semantic Drift (lev...
7,وقف الجواد الخبيث فجأة،,وقف الحصان الشرير فجأة.,وقف الجواد فجأة.,وقف الجواد فجأة.,4,5.000,1.000,0.000,0.5000,4,...,0.4733,True,False,True,False,0.6306,0.9272,0.9272,Flag,Semantic Drift (level_1) | Order Violation
13,والجو مطلولا لا تخلص معه الأنفاس.,والسماء تمطر، فلا يمكن رؤية شيء من خلال الضباب...,والسماء صافية ولا يوجد أي ضباب.,والسماء ملبدة بالغيوم لا يتخلص منها الهواء.,6,4.500,1.000,0.167,0.5300,10,...,0.5914,True,True,True,True,0.4864,0.2416,0.7191,Flag,Semantic Drift (level_1) | Semantic Drift (lev...
15,وكثيرا ما ثنته عما يقصد إليه،,ثنيه كثيراً عن ما يريد.,وكثيرا ما يثنيه الآخرون عما يريد فعله.,وكثيرا ما حالت بينه وبين هدفه.,6,4.000,1.000,0.000,0.4600,5,...,0.4600,True,True,False,False,0.6778,0.5544,0.7209,Flag,Semantic Drift (level_1) | Semantic Drift (lev...
20,تكسو الحشائش جانبي مجراها،,الحشائش تتسلل حول جوانب طريقها.,تغطي الأعشاب الجانبين.,تغطي الأعشاب الجانبين.,4,5.750,1.000,0.500,0.6800,5,...,0.7533,True,True,True,True,0.5843,0.5604,0.5604,Flag,Semantic Drift (level_1) | Semantic Drift (lev...
24,وكان المنظر من حوله مؤلفا من عناصر إذا اجتمعت،,كان المنظر من حوله ممتعا.,كان المنظر من حوله عبارة عن مجموعة من العناصر ...,وكان المنظر من حوله مزيجاً من العناصر التي إذا...,9,4.222,0.889,0.111,0.4689,5,...,0.4720,True,True,False,False,0.5555,0.9247,0.9476,Flag,Semantic Drift (level_1) | Order Violation
29,ومنعت الذكرى أن تحرك الأسف على فائت،,الذكرى تذكرنا بالأشياء التي فاتتنا.,الذكرى منعتني من الحزن على ما فات.,ومنعت الذكرى أن تُحَرِّكَ الأسف على فائِتٍ.,7,4.286,1.000,0.000,0.4714,5,...,0.4657,False,False,True,False,0.5742,0.8132,0.8574,Flag,Semantic Drift (level_1) | Order Violation
30,أو الرغبة أن تدفع إلى سعي.,أريد أن أبحث عن أشياء جديدة.,أريد أن أسعى وأبذل جهدي لتحقيق رغباتي.,أريد أن تسعى لتحقيق رغباتك.,6,3.333,1.000,0.000,0.4333,6,...,0.4760,False,True,False,False,0.3046,0.6799,0.7412,Flag,Semantic Drift (level_1) | Semantic Drift (lev...
32,ومن خلفه هو أرض بعضها مرعى فيما يعلم،,ومن خلفه أرض خضراء واسعة.,ومن خلفه أرض بعضها مرعى.,ومن خلفه أرض بعضها مرعى.,8,3.750,1.000,0.000,0.4500,5,...,0.4520,False,False,True,False,0.6095,0.8016,0.8016,Flag,Semantic Drift (level_1) | Order Violation

In [16]:
final_df.to_csv("cleaned_dataset2.csv", index=False)

In [17]:
flagged_df.to_csv("flagged.csv", index=False)

# Allam the flagged

In [18]:
import torch
import gc

# Delete the old semantic model and any previous ALLaM attempts if they exist in memory
try:
    del model
    del tokenizer
    del orig_emb
    del lvl_emb
except NameError:
    pass

# Force Python's garbage collector to run
gc.collect()

# Force PyTorch to empty the GPU cache
torch.cuda.empty_cache()

print(f"Memory cleared! GPU is now free: {torch.cuda.memory_allocated() / 1024**2:.2f} MB used.")

Memory cleared! GPU is now free: 9.12 MB used.

In [19]:
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig

MODEL_ID = "humain-ai/ALLaM-7B-Instruct-preview"

print("1. Loading tokenizer...")
tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)

print("2. Configuring 4-bit compression...")
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.float16, 
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4"
)

print("3. Streaming model directly to GPU (Watch your System RAM!)...")
# These parameters are the strictest possible way to save CPU RAM
model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    device_map={"": 0},      # Forces direct-to-GPU loading (GPU 0)
    quantization_config=bnb_config,
    low_cpu_mem_usage=True   # Instructs PyTorch to be extremely careful with RAM
)

model.eval()
print("🎉 Model loaded successfully!")

1. Loading tokenizer...

config.json:   0%|          | 0.00/686 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.model:   0%|          | 0.00/1.23M [00:00<?, ?B/s]

2. Configuring 4-bit compression...
3. Streaming model directly to GPU (Watch your System RAM!)...

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 3 files:   0%|          | 0/3 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/111 [00:00<?, ?B/s]

🎉 Model loaded successfully!

In [20]:
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig

MODEL_ID = "humain-ai/ALLaM-7B-Instruct-preview"

print("Loading tokenizer...")
tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.float16, 
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4"
)

print("Loading model carefully to prevent RAM crash...")

model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    device_map="auto",
    quantization_config=bnb_config,
    low_cpu_mem_usage=True  # <-- THIS PREVENTS THE KERNEL CRASH
)

model.eval()
print("Model loaded successfully in 4-bit!")

Loading tokenizer...
Loading model carefully to prevent RAM crash...

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

KeyboardInterrupt:

In [23]:
import pandas as pd

flagged_df = pd.read_csv("/kaggle/working/flagged.csv")

In [24]:
import re

def build_fast_prompt(original, l1, l2, l3):
    return f"""أنت مقيم لغوي صارم. اكتشف أي تلاعب في المعنى أو أخطاء لغوية في التبسيط.
النص الأصلي: "{original}"
المستوى 1: "{l1}"
المستوى 2: "{l2}"
المستوى 3: "{l3}"

انحراف المعنى: هل تغير المعنى الأصلي تماماً؟ هل هناك أخطاء واضحة؟
أجب باختصار شديد جداً باستخدام هذا التنسيق بالضبط (سطرين فقط):
التقييم: [اكتب فقط Pass أو Moderate أو Flag]
السبب: [اكتب السبب في جملة واحدة قصيرة جداً، أو اكتب None]"""

def evaluate_row_with_allam(original, l1, l2, l3):
    orig_str, l1_str, l2_str, l3_str = str(original), str(l1), str(l2), str(l3)
    
    # صائد الـ NaN السريع (يوفر وقت الـ GPU)
    if any(val in ["nan", "NaN", "", "None"] for val in [orig_str, l1_str, l2_str, l3_str]):
        return {"evaluation_status": "Flag", "issue_details": "بيانات مفقودة (NaN)"}

    messages = [
        {"role": "system", "content": "أنت مقيم لغوي دقيق. تجيب بوضوح وباختصار شديد."},
        {"role": "user", "content": build_fast_prompt(orig_str, l1_str, l2_str, l3_str)}
    ]
    
    prompt_text = tokenizer.apply_chat_template(
        messages, 
        add_generation_prompt=True, 
        tokenize=False
    )
    
    inputs = tokenizer(prompt_text, return_tensors="pt").to(model.device)
    
    with torch.no_grad():
        output_ids = model.generate(
            **inputs,
            max_new_tokens=100, 
            temperature=0.1,
            do_sample=True,
            pad_token_id=tokenizer.eos_token_id
        )
        
    input_length = inputs['input_ids'].shape[1]
    response_tokens = output_ids[0][input_length:]
    response_text = tokenizer.decode(response_tokens, skip_special_tokens=True)
    
    # استخراج البيانات من النص العادي (بدون JSON)
    status = "Flag" # التقييم الافتراضي
    details = "تعذر تحديد السبب"
    
    # 1. البحث عن التقييم
    if re.search(r'(?i)التقييم:\s*Pass', response_text):
        status = "Pass"
    elif re.search(r'(?i)التقييم:\s*Moderate', response_text):
        status = "Moderate"
    elif re.search(r'(?i)التقييم:\s*Flag', response_text):
        status = "Flag"
        
    # 2. البحث عن السبب
    details_match = re.search(r'السبب:\s*(.*)', response_text)
    if details_match:
        details = details_match.group(1).strip()
    
    return {"evaluation_status": status, "issue_details": details}

In [25]:
def process_dataframe(df: pd.DataFrame) -> pd.DataFrame:
    statuses = []
    details = []
    
    print(f"Evaluating {len(df)} rows using ALLaM...")
    
    for index, row in df.iterrows():
        result = evaluate_row_with_allam(
            row.get('Original_Sentence', ''), 
            row.get('level_1', ''), 
            row.get('level_2', ''), 
            row.get('level_3', '')
        )
        
        statuses.append(result.get("evaluation_status", "Flag"))
        details.append(result.get("issue_details", "Parse Error"))
        
        if (index + 1) % 5 == 0:
            print(f"Processed {index + 1}/{len(df)} rows...")

    df["evaluation_status"] = statuses
    df["issue_details"] = details
    return df
final_2df = process_dataframe(flagged_df[["Original_Sentence","level_1","level_2","level_3"]].copy())
display(final_2df[["Original_Sentence", "evaluation_status", "issue_details"]].head())
# Example Execution:
# df_raw = pd.read_csv("your_data.csv")
# final_df = process_dataframe(df_raw)
# display(final_df[["original", "evaluation_status", "issue_details"]].head())

Evaluating 6457 rows using ALLaM...
Processed 5/6457 rows...
Processed 10/6457 rows...
Processed 15/6457 rows...
Processed 20/6457 rows...
Processed 25/6457 rows...
Processed 30/6457 rows...
Processed 35/6457 rows...
Processed 40/6457 rows...
Processed 45/6457 rows...
Processed 50/6457 rows...
Processed 55/6457 rows...
Processed 60/6457 rows...
Processed 65/6457 rows...
Processed 70/6457 rows...
Processed 75/6457 rows...
Processed 80/6457 rows...
Processed 85/6457 rows...
Processed 90/6457 rows...
Processed 95/6457 rows...
Processed 100/6457 rows...
Processed 105/6457 rows...
Processed 110/6457 rows...
Processed 115/6457 rows...
Processed 120/6457 rows...
Processed 125/6457 rows...
Processed 130/6457 rows...
Processed 135/6457 rows...
Processed 140/6457 rows...
Processed 145/6457 rows...
Processed 150/6457 rows...
Processed 155/6457 rows...
Processed 160/6457 rows...
Processed 165/6457 rows...
Processed 170/6457 rows...
Processed 175/6457 rows...
Processed 180/6457 rows...
Processed 185/6457 rows...
Processed 190/6457 rows...
Processed 195/6457 rows...
Processed 200/6457 rows...
Processed 205/6457 rows...
Processed 210/6457 rows...
Processed 215/6457 rows...
Processed 220/6457 rows...
Processed 225/6457 rows...
Processed 230/6457 rows...
Processed 235/6457 rows...
Processed 240/6457 rows...
Processed 245/6457 rows...
Processed 250/6457 rows...
Processed 255/6457 rows...
Processed 260/6457 rows...
Processed 265/6457 rows...
Processed 270/6457 rows...
Processed 275/6457 rows...
Processed 280/6457 rows...
Processed 285/6457 rows...
Processed 290/6457 rows...
Processed 295/6457 rows...
Processed 300/6457 rows...
Processed 305/6457 rows...
Processed 310/6457 rows...
Processed 315/6457 rows...
Processed 320/6457 rows...
Processed 325/6457 rows...
Processed 330/6457 rows...
Processed 335/6457 rows...
Processed 340/6457 rows...
Processed 345/6457 rows...
Processed 350/6457 rows...
Processed 355/6457 rows...
Processed 360/6457 rows...
Processed 365/6457 rows...
Processed 370/6457 rows...
Processed 375/6457 rows...
Processed 380/6457 rows...
Processed 385/6457 rows...
Processed 390/6457 rows...
Processed 395/6457 rows...
Processed 400/6457 rows...
Processed 405/6457 rows...
Processed 410/6457 rows...
Processed 415/6457 rows...
Processed 420/6457 rows...
Processed 425/6457 rows...
Processed 430/6457 rows...
Processed 435/6457 rows...
Processed 440/6457 rows...
Processed 445/6457 rows...
Processed 450/6457 rows...
Processed 455/6457 rows...
Processed 460/6457 rows...
Processed 465/6457 rows...
Processed 470/6457 rows...
Processed 475/6457 rows...
Processed 480/6457 rows...
Processed 485/6457 rows...
Processed 490/6457 rows...
Processed 495/6457 rows...
Processed 500/6457 rows...
Processed 505/6457 rows...
Processed 510/6457 rows...
Processed 515/6457 rows...
Processed 520/6457 rows...
Processed 525/6457 rows...
Processed 530/6457 rows...
Processed 535/6457 rows...
Processed 540/6457 rows...
Processed 545/6457 rows...
Processed 550/6457 rows...
Processed 555/6457 rows...
Processed 560/6457 rows...
Processed 565/6457 rows...
Processed 570/6457 rows...
Processed 575/6457 rows...
Processed 580/6457 rows...
Processed 585/6457 rows...
Processed 590/6457 rows...
Processed 595/6457 rows...
Processed 600/6457 rows...
Processed 605/6457 rows...
Processed 610/6457 rows...
Processed 615/6457 rows...
Processed 620/6457 rows...
Processed 625/6457 rows...
Processed 630/6457 rows...
Processed 635/6457 rows...
Processed 640/6457 rows...
Processed 645/6457 rows...
Processed 650/6457 rows...
Processed 655/6457 rows...
Processed 660/6457 rows...
Processed 665/6457 rows...
Processed 670/6457 rows...
Processed 675/6457 rows...
Processed 680/6457 rows...
Processed 685/6457 rows...
Processed 690/6457 rows...
Processed 695/6457 rows...
Processed 700/6457 rows...
Processed 705/6457 rows...
Processed 710/6457 rows...
Processed 715/6457 rows...
Processed 720/6457 rows...
Processed 725/6457 rows...
Processed 730/6457 rows...
Processed 735/6457 rows...
Processed 740/6457 rows...
Processed 745/6457 rows...
Processed 750/6457 rows...
Processed 755/6457 rows...
Processed 760/6457 rows...
Processed 765/6457 rows...
Processed 770/6457 rows...
Processed 775/6457 rows...
Processed 780/6457 rows...
Processed 785/6457 rows...
Processed 790/6457 rows...
Processed 795/6457 rows...
Processed 800/6457 rows...
Processed 805/6457 rows...
Processed 810/6457 rows...
Processed 815/6457 rows...
Processed 820/6457 rows...
Processed 825/6457 rows...
Processed 830/6457 rows...
Processed 835/6457 rows...
Processed 840/6457 rows...
Processed 845/6457 rows...
Processed 850/6457 rows...
Processed 855/6457 rows...
Processed 860/6457 rows...
Processed 865/6457 rows...
Processed 870/6457 rows...
Processed 875/6457 rows...
Processed 880/6457 rows...
Processed 885/6457 rows...
Processed 890/6457 rows...
Processed 895/6457 rows...
Processed 900/6457 rows...
Processed 905/6457 rows...
Processed 910/6457 rows...
Processed 915/6457 rows...
Processed 920/6457 rows...
Processed 925/6457 rows...
Processed 930/6457 rows...
Processed 935/6457 rows...
Processed 940/6457 rows...
Processed 945/6457 rows...
Processed 950/6457 rows...
Processed 955/6457 rows...
Processed 960/6457 rows...
Processed 965/6457 rows...
Processed 970/6457 rows...
Processed 975/6457 rows...
Processed 980/6457 rows...
Processed 985/6457 rows...
Processed 990/6457 rows...
Processed 995/6457 rows...
Processed 1000/6457 rows...
Processed 1005/6457 rows...
Processed 1010/6457 rows...
Processed 1015/6457 rows...
Processed 1020/6457 rows...
Processed 1025/6457 rows...
Processed 1030/6457 rows...
Processed 1035/6457 rows...
Processed 1040/6457 rows...
Processed 1045/6457 rows...
Processed 1050/6457 rows...
Processed 1055/6457 rows...
Processed 1060/6457 rows...
Processed 1065/6457 rows...
Processed 1070/6457 rows...
Processed 1075/6457 rows...
Processed 1080/6457 rows...
Processed 1085/6457 rows...
Processed 1090/6457 rows...
Processed 1095/6457 rows...
Processed 1100/6457 rows...
Processed 1105/6457 rows...
Processed 1110/6457 rows...
Processed 1115/6457 rows...
Processed 1120/6457 rows...
Processed 1125/6457 rows...
Processed 1130/6457 rows...
Processed 1135/6457 rows...
Processed 1140/6457 rows...
Processed 1145/6457 rows...
Processed 1150/6457 rows...
Processed 1155/6457 rows...
Processed 1160/6457 rows...
Processed 1165/6457 rows...
Processed 1170/6457 rows...
Processed 1175/6457 rows...
Processed 1180/6457 rows...
Processed 1185/6457 rows...
Processed 1190/6457 rows...
Processed 1195/6457 rows...
Processed 1200/6457 rows...
Processed 1205/6457 rows...
Processed 1210/6457 rows...
Processed 1215/6457 rows...
Processed 1220/6457 rows...
Processed 1225/6457 rows...
Processed 1230/6457 rows...
Processed 1235/6457 rows...
Processed 1240/6457 rows...
Processed 1245/6457 rows...
Processed 1250/6457 rows...
Processed 1255/6457 rows...
Processed 1260/6457 rows...
Processed 1265/6457 rows...
Processed 1270/6457 rows...
Processed 1275/6457 rows...
Processed 1280/6457 rows...
Processed 1285/6457 rows...
Processed 1290/6457 rows...
Processed 1295/6457 rows...
Processed 1300/6457 rows...
Processed 1305/6457 rows...
Processed 1310/6457 rows...
Processed 1315/6457 rows...
Processed 1320/6457 rows...
Processed 1325/6457 rows...
Processed 1330/6457 rows...
Processed 1335/6457 rows...
Processed 1340/6457 rows...
Processed 1345/6457 rows...
Processed 1350/6457 rows...
Processed 1355/6457 rows...
Processed 1360/6457 rows...
Processed 1365/6457 rows...
Processed 1370/6457 rows...
Processed 1375/6457 rows...
Processed 1380/6457 rows...
Processed 1385/6457 rows...
Processed 1390/6457 rows...
Processed 1395/6457 rows...
Processed 1400/6457 rows...
Processed 1405/6457 rows...
Processed 1410/6457 rows...
Processed 1415/6457 rows...
Processed 1420/6457 rows...
Processed 1425/6457 rows...
Processed 1430/6457 rows...
Processed 1435/6457 rows...
Processed 1440/6457 rows...
Processed 1445/6457 rows...
Processed 1450/6457 rows...
Processed 1455/6457 rows...
Processed 1460/6457 rows...
Processed 1465/6457 rows...
Processed 1470/6457 rows...
Processed 1475/6457 rows...
Processed 1480/6457 rows...
Processed 1485/6457 rows...
Processed 1490/6457 rows...
Processed 1495/6457 rows...
Processed 1500/6457 rows...
Processed 1505/6457 rows...
Processed 1510/6457 rows...
Processed 1515/6457 rows...
Processed 1520/6457 rows...
Processed 1525/6457 rows...
Processed 1530/6457 rows...
Processed 1535/6457 rows...
Processed 1540/6457 rows...
Processed 1545/6457 rows...
Processed 1550/6457 rows...
Processed 1555/6457 rows...
Processed 1560/6457 rows...
Processed 1565/6457 rows...
Processed 1570/6457 rows...
Processed 1575/6457 rows...
Processed 1580/6457 rows...
Processed 1585/6457 rows...
Processed 1590/6457 rows...
Processed 1595/6457 rows...
Processed 1600/6457 rows...
Processed 1605/6457 rows...
Processed 1610/6457 rows...
Processed 1615/6457 rows...
Processed 1620/6457 rows...
Processed 1625/6457 rows...
Processed 1630/6457 rows...
Processed 1635/6457 rows...
Processed 1640/6457 rows...
Processed 1645/6457 rows...
Processed 1650/6457 rows...
Processed 1655/6457 rows...
Processed 1660/6457 rows...
Processed 1665/6457 rows...
Processed 1670/6457 rows...
Processed 1675/6457 rows...
Processed 1680/6457 rows...
Processed 1685/6457 rows...
Processed 1690/6457 rows...
Processed 1695/6457 rows...
Processed 1700/6457 rows...
Processed 1705/6457 rows...
Processed 1710/6457 rows...
Processed 1715/6457 rows...
Processed 1720/6457 rows...
Processed 1725/6457 rows...
Processed 1730/6457 rows...
Processed 1735/6457 rows...
Processed 1740/6457 rows...
Processed 1745/6457 rows...
Processed 1750/6457 rows...
Processed 1755/6457 rows...
Processed 1760/6457 rows...
Processed 1765/6457 rows...
Processed 1770/6457 rows...
Processed 1775/6457 rows...
Processed 1780/6457 rows...
Processed 1785/6457 rows...
Processed 1790/6457 rows...
Processed 1795/6457 rows...
Processed 1800/6457 rows...
Processed 1805/6457 rows...
Processed 1810/6457 rows...
Processed 1815/6457 rows...
Processed 1820/6457 rows...
Processed 1825/6457 rows...
Processed 1830/6457 rows...
Processed 1835/6457 rows...
Processed 1840/6457 rows...
Processed 1845/6457 rows...
Processed 1850/6457 rows...
Processed 1855/6457 rows...
Processed 1860/6457 rows...
Processed 1865/6457 rows...
Processed 1870/6457 rows...
Processed 1875/6457 rows...
Processed 1880/6457 rows...
Processed 1885/6457 rows...
Processed 1890/6457 rows...
Processed 1895/6457 rows...
Processed 1900/6457 rows...
Processed 1905/6457 rows...
Processed 1910/6457 rows...
Processed 1915/6457 rows...
Processed 1920/6457 rows...
Processed 1925/6457 rows...
Processed 1930/6457 rows...
Processed 1935/6457 rows...
Processed 1940/6457 rows...
Processed 1945/6457 rows...
Processed 1950/6457 rows...
Processed 1955/6457 rows...
Processed 1960/6457 rows...
Processed 1965/6457 rows...
Processed 1970/6457 rows...
Processed 1975/6457 rows...
Processed 1980/6457 rows...
Processed 1985/6457 rows...
Processed 1990/6457 rows...
Processed 1995/6457 rows...
Processed 2000/6457 rows...
Processed 2005/6457 rows...
Processed 2010/6457 rows...
Processed 2015/6457 rows...
Processed 2020/6457 rows...
Processed 2025/6457 rows...
Processed 2030/6457 rows...
Processed 2035/6457 rows...
Processed 2040/6457 rows...
Processed 2045/6457 rows...
Processed 2050/6457 rows...
Processed 2055/6457 rows...
Processed 2060/6457 rows...
Processed 2065/6457 rows...
Processed 2070/6457 rows...
Processed 2075/6457 rows...
Processed 2080/6457 rows...
Processed 2085/6457 rows...
Processed 2090/6457 rows...
Processed 2095/6457 rows...
Processed 2100/6457 rows...
Processed 2105/6457 rows...
Processed 2110/6457 rows...
Processed 2115/6457 rows...
Processed 2120/6457 rows...
Processed 2125/6457 rows...
Processed 2130/6457 rows...
Processed 2135/6457 rows...
Processed 2140/6457 rows...
Processed 2145/6457 rows...
Processed 2150/6457 rows...
Processed 2155/6457 rows...
Processed 2160/6457 rows...
Processed 2165/6457 rows...
Processed 2170/6457 rows...
Processed 2175/6457 rows...
Processed 2180/6457 rows...
Processed 2185/6457 rows...
Processed 2190/6457 rows...
Processed 2195/6457 rows...
Processed 2200/6457 rows...
Processed 2205/6457 rows...
Processed 2210/6457 rows...
Processed 2215/6457 rows...
Processed 2220/6457 rows...
Processed 2225/6457 rows...
Processed 2230/6457 rows...
Processed 2235/6457 rows...
Processed 2240/6457 rows...
Processed 2245/6457 rows...
Processed 2250/6457 rows...
Processed 2255/6457 rows...
Processed 2260/6457 rows...
Processed 2265/6457 rows...
Processed 2270/6457 rows...
Processed 2275/6457 rows...
Processed 2280/6457 rows...
Processed 2285/6457 rows...
Processed 2290/6457 rows...
Processed 2295/6457 rows...
Processed 2300/6457 rows...
Processed 2305/6457 rows...
Processed 2310/6457 rows...
Processed 2315/6457 rows...
Processed 2320/6457 rows...
Processed 2325/6457 rows...
Processed 2330/6457 rows...
Processed 2335/6457 rows...
Processed 2340/6457 rows...
Processed 2345/6457 rows...
Processed 2350/6457 rows...
Processed 2355/6457 rows...
Processed 2360/6457 rows...
Processed 2365/6457 rows...
Processed 2370/6457 rows...
Processed 2375/6457 rows...
Processed 2380/6457 rows...
Processed 2385/6457 rows...
Processed 2390/6457 rows...
Processed 2395/6457 rows...
Processed 2400/6457 rows...
Processed 2405/6457 rows...
Processed 2410/6457 rows...
Processed 2415/6457 rows...
Processed 2420/6457 rows...
Processed 2425/6457 rows...
Processed 2430/6457 rows...
Processed 2435/6457 rows...
Processed 2440/6457 rows...
Processed 2445/6457 rows...
Processed 2450/6457 rows...
Processed 2455/6457 rows...
Processed 2460/6457 rows...
Processed 2465/6457 rows...
Processed 2470/6457 rows...
Processed 2475/6457 rows...
Processed 2480/6457 rows...
Processed 2485/6457 rows...
Processed 2490/6457 rows...
Processed 2495/6457 rows...
Processed 2500/6457 rows...
Processed 2505/6457 rows...
Processed 2510/6457 rows...
Processed 2515/6457 rows...
Processed 2520/6457 rows...
Processed 2525/6457 rows...
Processed 2530/6457 rows...
Processed 2535/6457 rows...
Processed 2540/6457 rows...
Processed 2545/6457 rows...
Processed 2550/6457 rows...
Processed 2555/6457 rows...
Processed 2560/6457 rows...
Processed 2565/6457 rows...
Processed 2570/6457 rows...
Processed 2575/6457 rows...
Processed 2580/6457 rows...
Processed 2585/6457 rows...
Processed 2590/6457 rows...
Processed 2595/6457 rows...
Processed 2600/6457 rows...
Processed 2605/6457 rows...
Processed 2610/6457 rows...
Processed 2615/6457 rows...
Processed 2620/6457 rows...
Processed 2625/6457 rows...
Processed 2630/6457 rows...
Processed 2635/6457 rows...
Processed 2640/6457 rows...
Processed 2645/6457 rows...
Processed 2650/6457 rows...
Processed 2655/6457 rows...
Processed 2660/6457 rows...
Processed 2665/6457 rows...
Processed 2670/6457 rows...
Processed 2675/6457 rows...
Processed 2680/6457 rows...
Processed 2685/6457 rows...
Processed 2690/6457 rows...
Processed 2695/6457 rows...
Processed 2700/6457 rows...
Processed 2705/6457 rows...
Processed 2710/6457 rows...
Processed 2715/6457 rows...
Processed 2720/6457 rows...
Processed 2725/6457 rows...
Processed 2730/6457 rows...
Processed 2735/6457 rows...
Processed 2740/6457 rows...
Processed 2745/6457 rows...
Processed 2750/6457 rows...
Processed 2755/6457 rows...
Processed 2760/6457 rows...
Processed 2765/6457 rows...
Processed 2770/6457 rows...
Processed 2775/6457 rows...
Processed 2780/6457 rows...
Processed 2785/6457 rows...
Processed 2790/6457 rows...
Processed 2795/6457 rows...
Processed 2800/6457 rows...
Processed 2805/6457 rows...
Processed 2810/6457 rows...
Processed 2815/6457 rows...
Processed 2820/6457 rows...
Processed 2825/6457 rows...
Processed 2830/6457 rows...
Processed 2835/6457 rows...
Processed 2840/6457 rows...
Processed 2845/6457 rows...
Processed 2850/6457 rows...
Processed 2855/6457 rows...
Processed 2860/6457 rows...
Processed 2865/6457 rows...
Processed 2870/6457 rows...
Processed 2875/6457 rows...
Processed 2880/6457 rows...
Processed 2885/6457 rows...
Processed 2890/6457 rows...
Processed 2895/6457 rows...
Processed 2900/6457 rows...
Processed 2905/6457 rows...
Processed 2910/6457 rows...
Processed 2915/6457 rows...
Processed 2920/6457 rows...
Processed 2925/6457 rows...
Processed 2930/6457 rows...
Processed 2935/6457 rows...
Processed 2940/6457 rows...
Processed 2945/6457 rows...
Processed 2950/6457 rows...
Processed 2955/6457 rows...
Processed 2960/6457 rows...
Processed 2965/6457 rows...
Processed 2970/6457 rows...
Processed 2975/6457 rows...
Processed 2980/6457 rows...
Processed 2985/6457 rows...
Processed 2990/6457 rows...
Processed 2995/6457 rows...
Processed 3000/6457 rows...
Processed 3005/6457 rows...
Processed 3010/6457 rows...
Processed 3015/6457 rows...
Processed 3020/6457 rows...
Processed 3025/6457 rows...
Processed 3030/6457 rows...
Processed 3035/6457 rows...
Processed 3040/6457 rows...
Processed 3045/6457 rows...
Processed 3050/6457 rows...
Processed 3055/6457 rows...
Processed 3060/6457 rows...
Processed 3065/6457 rows...
Processed 3070/6457 rows...
Processed 3075/6457 rows...
Processed 3080/6457 rows...
Processed 3085/6457 rows...
Processed 3090/6457 rows...
Processed 3095/6457 rows...
Processed 3100/6457 rows...
Processed 3105/6457 rows...
Processed 3110/6457 rows...
Processed 3115/6457 rows...
Processed 3120/6457 rows...
Processed 3125/6457 rows...
Processed 3130/6457 rows...
Processed 3135/6457 rows...
Processed 3140/6457 rows...
Processed 3145/6457 rows...
Processed 3150/6457 rows...
Processed 3155/6457 rows...
Processed 3160/6457 rows...
Processed 3165/6457 rows...
Processed 3170/6457 rows...
Processed 3175/6457 rows...
Processed 3180/6457 rows...
Processed 3185/6457 rows...
Processed 3190/6457 rows...
Processed 3195/6457 rows...
Processed 3200/6457 rows...
Processed 3205/6457 rows...
Processed 3210/6457 rows...
Processed 3215/6457 rows...
Processed 3220/6457 rows...
Processed 3225/6457 rows...
Processed 3230/6457 rows...
Processed 3235/6457 rows...
Processed 3240/6457 rows...
Processed 3245/6457 rows...
Processed 3250/6457 rows...
Processed 3255/6457 rows...
Processed 3260/6457 rows...
Processed 3265/6457 rows...
Processed 3270/6457 rows...
Processed 3275/6457 rows...
Processed 3280/6457 rows...
Processed 3285/6457 rows...
Processed 3290/6457 rows...
Processed 3295/6457 rows...
Processed 3300/6457 rows...
Processed 3305/6457 rows...
Processed 3310/6457 rows...
Processed 3315/6457 rows...
Processed 3320/6457 rows...
Processed 3325/6457 rows...
Processed 3330/6457 rows...
Processed 3335/6457 rows...
Processed 3340/6457 rows...
Processed 3345/6457 rows...
Processed 3350/6457 rows...
Processed 3355/6457 rows...
Processed 3360/6457 rows...
Processed 3365/6457 rows...
Processed 3370/6457 rows...
Processed 3375/6457 rows...
Processed 3380/6457 rows...
Processed 3385/6457 rows...
Processed 3390/6457 rows...
Processed 3395/6457 rows...
Processed 3400/6457 rows...
Processed 3405/6457 rows...
Processed 3410/6457 rows...
Processed 3415/6457 rows...
Processed 3420/6457 rows...
Processed 3425/6457 rows...
Processed 3430/6457 rows...
Processed 3435/6457 rows...
Processed 3440/6457 rows...
Processed 3445/6457 rows...
Processed 3450/6457 rows...
Processed 3455/6457 rows...
Processed 3460/6457 rows...
Processed 3465/6457 rows...
Processed 3470/6457 rows...
Processed 3475/6457 rows...
Processed 3480/6457 rows...
Processed 3485/6457 rows...
Processed 3490/6457 rows...
Processed 3495/6457 rows...
Processed 3500/6457 rows...
Processed 3505/6457 rows...
Processed 3510/6457 rows...
Processed 3515/6457 rows...
Processed 3520/6457 rows...
Processed 3525/6457 rows...
Processed 3530/6457 rows...
Processed 3535/6457 rows...
Processed 3540/6457 rows...
Processed 3545/6457 rows...
Processed 3550/6457 rows...
Processed 3555/6457 rows...
Processed 3560/6457 rows...
Processed 3565/6457 rows...
Processed 3570/6457 rows...
Processed 3575/6457 rows...
Processed 3580/6457 rows...
Processed 3585/6457 rows...
Processed 3590/6457 rows...
Processed 3595/6457 rows...
Processed 3600/6457 rows...

,Original_Sentence,evaluation_status,issue_details
0,الفصل الثاني,Flag,بيانات مفقودة (NaN)
1,«وكان صباح..,Flag,بيانات مفقودة (NaN)
2,وقف الجواد الخبيث فجأة،,Pass,لا توجد أخطاء واضحة أو انحراف في المعنى.
3,والجو مطلولا لا تخلص معه الأنفاس.,Flag,المعنى الأصلي يشير إلى جو مطير يعيق التنفس، بي...
4,وكثيرا ما ثنته عما يقصد إليه،,Flag,"الجملة ""ثنيه كثيراً عن ما يريد"" غير صحيحة لغوياً."

In [26]:
display(final_2df.head(20))

,Original_Sentence,level_1,level_2,level_3,evaluation_status,issue_details
0,الفصل الثاني,الفصل التاني,NaN,NaN,Flag,بيانات مفقودة (NaN)
1,«وكان صباح..,كان يوم جميل.,كان يوماً جميلاً.,NaN,Flag,بيانات مفقودة (NaN)
2,وقف الجواد الخبيث فجأة،,وقف الحصان الشرير فجأة.,وقف الجواد فجأة.,وقف الجواد فجأة.,Pass,لا توجد أخطاء واضحة أو انحراف في المعنى.
3,والجو مطلولا لا تخلص معه الأنفاس.,والسماء تمطر، فلا يمكن رؤية شيء من خلال الضباب...,والسماء صافية ولا يوجد أي ضباب.,والسماء ملبدة بالغيوم لا يتخلص منها الهواء.,Flag,المعنى الأصلي يشير إلى جو مطير يعيق التنفس، بي...
4,وكثيرا ما ثنته عما يقصد إليه،,ثنيه كثيراً عن ما يريد.,وكثيرا ما يثنيه الآخرون عما يريد فعله.,وكثيرا ما حالت بينه وبين هدفه.,Flag,"الجملة ""ثنيه كثيراً عن ما يريد"" غير صحيحة لغوياً."
5,تكسو الحشائش جانبي مجراها،,الحشائش تتسلل حول جوانب طريقها.,تغطي الأعشاب الجانبين.,تغطي الأعشاب الجانبين.,Moderate,المستوى 1 يغير المعنى الأصلي.
6,وكان المنظر من حوله مؤلفا من عناصر إذا اجتمعت،,كان المنظر من حوله ممتعا.,كان المنظر من حوله عبارة عن مجموعة من العناصر ...,وكان المنظر من حوله مزيجاً من العناصر التي إذا...,Moderate,المستوى 3 يحتوي على خطأ نحوي.
7,ومنعت الذكرى أن تحرك الأسف على فائت،,الذكرى تذكرنا بالأشياء التي فاتتنا.,الذكرى منعتني من الحزن على ما فات.,ومنعت الذكرى أن تُحَرِّكَ الأسف على فائِتٍ.,Flag,الترجمة الثانية تحرف المعنى الأصلي.
8,أو الرغبة أن تدفع إلى سعي.,أريد أن أبحث عن أشياء جديدة.,أريد أن أسعى وأبذل جهدي لتحقيق رغباتي.,أريد أن تسعى لتحقيق رغباتك.,Flag,الجملة الأخيرة غير واضحة المعنى.
9,ومن خلفه هو أرض بعضها مرعى فيما يعلم،,ومن خلفه أرض خضراء واسعة.,ومن خلفه أرض بعضها مرعى.,ومن خلفه أرض بعضها مرعى.,Moderate,تغيير في المعنى الأصلي مع وجود أخطاء لغوية في ...
10,وكل ما حوله أشكال ليس لها معارف — كالدرهم المس...,حولَهُ أشكالٌ غريبةٌ لا يعرفُ معناها.,وكل ما حوله أشكال ليس لها معاني - مثل الدرهم ا...,وكل ما حوله أشكال ليس لها معاني - كحجر الصوان ...,Moderate,بعض الأخطاء في الوصف الدقيق للأشكال ومعانيها.
11,إذ كان الضباب لا يزال يكسوها ثوبا يزيدها في رأ...,كان الضباب يغطيها، فتبدو عارية أمام العين والقلب.,كان الضباب يكسوها، فتبدو عارية تجردت من ملابسها.,كان الضباب يكسوها، فبدت في نظرك عاريةٌ متجردةٌ.,Moderate,"تلاعب في استخدام كلمة ""تجردت""."
12,وكانت السماء دانية مسفة يحس المرء أنها تهم بال...,كانت السماء مظلمة ومهببة، وكان الهواء بارداً.,كانت السماء مظلمة وكأنها على وشك أن تمطر.,كانت السماء مظلمة وكأنها على وشك الانطباق على ...,Flag,"الجملة ""كانت السماء مظلمة وكأنها على وشك الانط..."
13,لا من فم آدمي.,ما يطلع من فم آدم.,لا أحد يولد متعلماً.,لا أحد يولد متعلماً.,Moderate,المستوى 1 يحرف المعنى الأصلي بشكل كبير.
14,فثنى خطواته إلى الدار،,دخل بسرعة إلى البيت.,دخل بخطوات متثاقلة نحو المنزل.,فَثَنَى وَقَفَ.,Flag,"تلاعب غير واضح في المعنى في ""فَثَنَى وَقَفَ""."
15,حتى طالعته زنجية لامعة الجلد،,كان يامكان كان هناك فيل لامع.,كان جلده لامعًا ومتألقًا.,حتى طالعته زنجية جلده لامعة.,Flag,تلاعب غير واضح في المعنى.
16,براقة الأسنان.,لأسنانك لمعان.,أسنانك تلمع.,لمع ناصية الشعر.,Flag,المعنى الأصلي غير واضح، والترجمة غير دقيقة.
17,واسعة العينين حمراؤهما،,عيونها حمراء واسعة.,عيونها حمراء واسعة.,عينيها واسعتان وحمراوان.,Flag,تلاعب في المعنى الأصلي.
18,حتى كأن ما نقص من هذا زيد في ذاك،,ناقص وزائد!,ما نقص من هذا زيد في ذاك.,ما نقص من هذا زيد في ذاك.,Flag,تلاعب في المعنى الأصلي.
19,ويلي الخصر ردفان ثقيلان تحتهما ساقان قصيرتان ك...,ويلي له بطن كبير، لديه ساقان قصيران.,ويلي الخصر ردفان ثقيلان وتحتهما ساقان قصيرتان.,وَلِيَ خَصْرُهُ رِدْفَانِ ثِقِيلَانِ تَحْتَهُم...,Moderate,"تغيير في وصف الأجزاء الجسدية، من ""ردفان ثقيلان..."

In [27]:
final_2df["evaluation_status"].value_counts()

evaluation_status
Flag        3942
Moderate    1786
Pass         729
Name: count, dtype: int64

In [28]:
final_2df.to_csv("final_2df.csv", index=False)

In [33]:
final_2df

,Original_Sentence,level_1,level_2,level_3,evaluation_status,issue_details
0,الفصل الثاني,الفصل التاني,NaN,NaN,Flag,بيانات مفقودة (NaN)
1,«وكان صباح..,كان يوم جميل.,كان يوماً جميلاً.,NaN,Flag,بيانات مفقودة (NaN)
2,وقف الجواد الخبيث فجأة،,وقف الحصان الشرير فجأة.,وقف الجواد فجأة.,وقف الجواد فجأة.,Pass,لا توجد أخطاء واضحة أو انحراف في المعنى.
3,والجو مطلولا لا تخلص معه الأنفاس.,والسماء تمطر، فلا يمكن رؤية شيء من خلال الضباب...,والسماء صافية ولا يوجد أي ضباب.,والسماء ملبدة بالغيوم لا يتخلص منها الهواء.,Flag,المعنى الأصلي يشير إلى جو مطير يعيق التنفس، بي...
4,وكثيرا ما ثنته عما يقصد إليه،,ثنيه كثيراً عن ما يريد.,وكثيرا ما يثنيه الآخرون عما يريد فعله.,وكثيرا ما حالت بينه وبين هدفه.,Flag,"الجملة ""ثنيه كثيراً عن ما يريد"" غير صحيحة لغوياً."
...,...,...,...,...,...,...
6452,ولكن الأمير جانبلاط يقيم اليوم في الشام نائبا ...,الأمير جانبلاط يعيش في الشام وهو نائب حلب.,يقيم اليوم الأمير جانبلاط في الشام نائبا عن حلب.,يقيم اليوم الأمير جانبلاط في الشام نائبا عن حلب.,Pass,المعنى الأصلي والمستويات 1 و 2 و 3 متطابقة، ول...
6453,لكأنما أراد أخوها قنصوه أن يحول بينها وبين لقياه،,أخاها كان يريد أن يمنعها من رؤيته.,أخاها كان كأنه يريد أن يمنعها من رؤيته.,لكأنه أراد أختها أن يبعدوه عنها لمنعه من لقائها.,Flag,تلاعب غير دقيق في المعنى.
6454,ومن أين له — وهو بعيد بعيد — أن يعرف أنه الساع...,ومن أين له أن يعرف أنه الساعة أن أماني تحب قاي...,ومن أين له أن يعرف أنه الساعة هو الرجل الوحيد ...,ومن أين له أن يعرف أنه الساعي، وهو البعيد، أن ...,Flag,تلاعب غير واضح في المعنى.
6455,وأم ولده السلطان الناصر!,وأمه تُحضر طعام ولده.,وأمّ ولده السلطان الناصر.,وأمَ أَولَدِه السُلطانَ الناصِرَ.,Flag,تلاعب غير واضح في المعنى.
6456,حسبها أن يذكرها جانبلاط،,جان بلاط ذكرها.,جانبلاط ذكرها.,حسبها جانبلاط تذكرها.,Flag,تلاعب غير واضح في المعنى.

# Now Concatenate

In [34]:
import pandas as pd

# 1. Load your datasets
# Replace these with your actual file names
df_a = pd.read_csv('/kaggle/working/cleaned_dataset2.csv')
df_b = final_2df.copy()

# 2. Clean the join key (remove whitespace and convert to string)
df_a['Original_Sentence'] = df_a['Original_Sentence'].astype(str).str.strip()
df_b['Original_Sentence'] = df_b['Original_Sentence'].astype(str).str.strip()

# 3. Create a subset of Table B with only the columns you want to update
# We only need the key and the columns to be replaced
columns_to_update = ['Original_Sentence', 'evaluation_status', 'issue_details']
df_b_subset = df_b[columns_to_update].copy()

# 4. Perform a left merge
# This keeps all rows from A and adds columns from B
merged_df = df_a.merge(
    df_b_subset, 
    on='Original_Sentence', 
    how='left', 
    suffixes=('', '_new')
)

# 5. Update the values
# Check if new data exists (is not null) and overwrite
mask = merged_df['evaluation_status_new'].notna()

merged_df.loc[mask, 'evaluation_status'] = merged_df.loc[mask, 'evaluation_status_new']
merged_df.loc[mask, 'issue_details'] = merged_df.loc[mask, 'issue_details_new']

# 6. Drop the temporary columns created by the merge
merged_df = merged_df.drop(columns=['evaluation_status_new', 'issue_details_new'])

In [36]:
# To remove duplicates and keep the first occurrence
merged_df.drop_duplicates(subset=['Original_Sentence'], inplace=True)

In [37]:
merged_df

,Original_Sentence,level_1,level_2,level_3,word_count__Original_Sentence,avg_word_len__Original_Sentence,unique_ratio__Original_Sentence,long_word_ratio__Original_Sentence,complexity_score__Original_Sentence,word_count__level_1,...,complexity_score__level_3,order_ok__orig_l1,order_ok__l1_l2,order_ok__l2_l3,order_valid,sem_sim__level_1,sem_sim__level_2,sem_sim__level_3,evaluation_status,issue_details
0,الفصل الثاني,الفصل التاني,NaN,NaN,2,5.500,1.0,0.000,0.5200,2,...,0.0000,True,False,True,False,0.7551,0.3324,0.3324,Flag,بيانات مفقودة (NaN)
9,«وكان صباح..,كان يوم جميل.,كان يوماً جميلاً.,NaN,2,4.000,1.0,0.000,0.4600,3,...,0.0000,True,True,False,False,0.5359,0.5311,0.2447,Flag,بيانات مفقودة (NaN)
10,يوما واحدا»,يوم واحد,يوما واحدا.,يوماً واحداً.,2,4.500,1.0,0.000,0.4800,2,...,0.4800,True,True,True,True,0.9808,0.9842,0.9730,Pass,NaN
11,قضى فتانا إبراهيم — وهذا اسمه — ليلة هادئة عمي...,إبراهيم قضى ليلة نوم عميق وهادئة، ما عدا حلم ق...,قضى إبراهيم، وهو اسم الفتى، ليلة هادئة ونال قس...,قضى إبراهيم، هذا هو اسمه، ليلة هادئة عميقة الن...,23,4.130,1.0,0.087,0.4913,21,...,0.4909,True,True,True,True,0.9143,0.9612,0.9498,Pass,NaN
12,ينحدر على أحد جانبيه نهر جائش،,ينحدر نهرٌ على جانب هذا المكان.,ينحدر نهرٌ على أحد جانبيه.,ينحدر نهرٌ على أحد جانبيه.,6,4.167,1.0,0.000,0.4667,6,...,0.4600,True,True,True,True,0.9307,0.9491,0.9491,Pass,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47254,ليته يدري!,ليته يعرف!,ليته يعرف!,ليته يشعر!,2,4.000,1.0,0.000,0.4600,2,...,0.4600,True,True,True,True,0.9885,0.9885,0.8273,Pass,NaN
47256,إذن لهدأ وجيب قلبها،,لقد هدأت وجاء قلبها.,لقد هدأت وجدبت قلبها.,لذلك هدأت وارتاحت.,4,4.250,1.0,0.000,0.4700,4,...,0.6000,True,True,True,True,0.8325,0.8309,0.6587,Moderate,Semantic Drift (level_3)
47257,واطمأنت إلى سعادة اليوم والغد.,سأكون سعيداً اليوم وغداً.,واطمئنت إلى سعادة اليوم والغد.,واطمئنت إلى سعادة اليوم والغد.,5,5.000,1.0,0.200,0.5600,4,...,0.5600,True,True,True,True,0.7992,0.9865,0.9865,Pass,NaN
47258,حسبها أن يذكرها جانبلاط،,جان بلاط ذكرها.,جانبلاط ذكرها.,حسبها جانبلاط تذكرها.,4,5.250,1.0,0.250,0.5850,3,...,0.6400,True,True,False,False,0.6938,0.8684,0.8856,Flag,تلاعب غير واضح في المعنى.
47259,وأن تطيف بخياله وبينهما ذلك البعد البعيد!,وأن يتخيل بينهم مسافة بعيدة!,وأن يتخيل بينهما مسافة بعيدة!,وأن يتجول بخياله بينهما!,7,4.857,1.0,0.143,0.5371,5,...,0.5000,True,True,True,True,0.8794,0.9030,0.8641,Pass,NaN

In [39]:

# 1. Load your datasets
# Replace these with your actual file names
df_a = pd.read_csv('/kaggle/input/datasets/rayaabualjamal/parrallel-bayyin-cleaned/full_merged_data.csv')
df_b = merged_df

# 1. Drop rows where 'evaluation_status' is 'flag'
# (We check if the column exists first just to be safe, in case only one df has it)
if 'evaluation_status' in df_a.columns:
    df_a = df_a[df_a['evaluation_status'] != 'flag']

if 'evaluation_status' in df_b.columns:
    df_b = df_b[df_b['evaluation_status'] != 'flag']

# 2. Concatenate the two dataframes
# ignore_index=True gives the new combined dataframe a fresh, clean index (0, 1, 2...)
df_combined = pd.concat([df_a, df_b], ignore_index=True)

# 3. Drop duplicated rows based on the 'original sentence' column
# keep='first' keeps the first instance it finds (from df_a). 
# If you want to prioritize df_b's version of the sentence, change this to keep='last'
df_final = df_combined.drop_duplicates(subset=['Original_Sentence'], keep='first')

# 7. Save the result
df_final.to_csv('Final.csv', index=False)

print("Merging complete.")

Merging complete.

In [42]:
df_final = df_combined.drop_duplicates(subset=['Original_Sentence'], keep='first')

In [43]:
df_final

,ID,level_1,level_2,level_3,Original_Sentence,word_count__Original_Sentence,avg_word_len__Original_Sentence,unique_ratio__Original_Sentence,long_word_ratio__Original_Sentence,complexity_score__Original_Sentence,...,complexity_score__level_3,order_ok__orig_l1,order_ok__l1_l2,order_ok__l2_l3,order_valid,sem_sim__level_1,sem_sim__level_2,sem_sim__level_3,evaluation_status,issue_details
0,10100300018,"""عدم الانحياز"" يعني أن تكون محايداً ولا تفضل أ...","""عدم الانحياز"" هو مصطلح سياسي يعني أن تكون محا...","""عدم الانحياز"" هو مصطلح سياسي يشير إلى الحياد.","•• ""عدم الانحياز"" اصطلاح سياسي يعنى الحياد..",6,5.333,1.00,0.167,0.5633,...,0.5175,True,True,True,True,0.7668,0.9523,0.9696,Pass,NaN
1,10100300019,الدول غير المنحازة لا تتعامل مع دول الشرق أو ا...,تلتزم الدول غير المنحازة بعدم التحالف مع دول ا...,تلتزم الدول غير المنحازة بالحياد وعدم التحالف ...,حيث تلتزم الدول غير المنحازة بعدم الارتباط بأي...,14,4.429,1.00,0.143,0.5200,...,0.5617,True,True,True,True,0.8315,0.9379,0.9125,Pass,NaN
2,10100300021,الدول غير المنحازة ليسوا متفرجين، هم يتدخلون و...,الدول غير المنحازة ليس لها موقف محايد في القضا...,بمعنى أن الدول غير المنحازة ليس موقفها موقف مت...,بمعنى أن الدول غير المنحازة لا تقف موقف المتفر...,25,4.560,0.92,0.280,0.5424,...,0.5384,False,False,False,False,0.8765,0.8955,0.9449,Moderate,Order Violation
3,10100300022,"وقد بدأ استخدام مصطلح ""عدم الانحياز"" في مؤتمر ...","وقد بدأ استخدام مصطلح ""عدم الانحياز"" في مؤتمر ...","وقد بدأ استعمال اصطلاح ""عدم الانحياز"" في مؤتمر...",وقد بدأ استعمال اصطلاح (عدم الانحياز) في مؤتمر...,17,4.353,1.00,0.118,0.5094,...,0.5071,True,True,False,False,0.9790,0.9831,0.9931,Moderate,Order Violation
4,10100300057,NaN,هيئة سياسية.,هيئة سياسية.,هيئة سياسية,2,5.000,1.00,0.000,0.5000,...,0.5000,True,True,True,True,0.3297,0.9865,0.9865,Moderate,Semantic Drift (level_1)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41731,NaN,ليته يعرف!,ليته يعرف!,ليته يشعر!,ليته يدري!,2,4.000,1.00,0.000,0.4600,...,0.4600,True,True,True,True,0.9885,0.9885,0.8273,Pass,NaN
41732,NaN,لقد هدأت وجاء قلبها.,لقد هدأت وجدبت قلبها.,لذلك هدأت وارتاحت.,إذن لهدأ وجيب قلبها،,4,4.250,1.00,0.000,0.4700,...,0.6000,True,True,True,True,0.8325,0.8309,0.6587,Moderate,Semantic Drift (level_3)
41733,NaN,سأكون سعيداً اليوم وغداً.,واطمئنت إلى سعادة اليوم والغد.,واطمئنت إلى سعادة اليوم والغد.,واطمأنت إلى سعادة اليوم والغد.,5,5.000,1.00,0.200,0.5600,...,0.5600,True,True,True,True,0.7992,0.9865,0.9865,Pass,NaN
41734,NaN,جان بلاط ذكرها.,جانبلاط ذكرها.,حسبها جانبلاط تذكرها.,حسبها أن يذكرها جانبلاط،,4,5.250,1.00,0.250,0.5850,...,0.6400,True,True,False,False,0.6938,0.8684,0.8856,Flag,تلاعب غير واضح في المعنى.
41735,NaN,وأن يتخيل بينهم مسافة بعيدة!,وأن يتخيل بينهما مسافة بعيدة!,وأن يتجول بخياله بينهما!,وأن تطيف بخياله وبينهما ذلك البعد البعيد!,7,4.857,1.00,0.143,0.5371,...,0.5000,True,True,True,True,0.8794,0.9030,0.8641,Pass,NaN

In [50]:
df_final.isnull().sum()

ID                                     19568
level_1                                    0
level_2                                    0
level_3                                    0
Original_Sentence                          0
word_count__Original_Sentence              0
avg_word_len__Original_Sentence            0
unique_ratio__Original_Sentence            0
long_word_ratio__Original_Sentence         0
complexity_score__Original_Sentence        0
word_count__level_1                        0
avg_word_len__level_1                      0
unique_ratio__level_1                      0
long_word_ratio__level_1                   0
complexity_score__level_1                  0
word_count__level_2                        0
avg_word_len__level_2                      0
unique_ratio__level_2                      0
long_word_ratio__level_2                   0
complexity_score__level_2                  0
word_count__level_3                        0
avg_word_len__level_3                      0
unique_ratio__level_3                      0
long_word_ratio__level_3                   0
complexity_score__level_3                  0
order_ok__orig_l1                          0
order_ok__l1_l2                            0
order_ok__l2_l3                            0
order_valid                                0
sem_sim__level_1                           0
sem_sim__level_2                           0
sem_sim__level_3                           0
evaluation_status                          0
issue_details                           8105
dtype: int64

In [48]:
# Drop rows where there are NaN values in 'column_name_1' or 'column_name_2'
df_final.dropna(subset=['level_1', 'level_2',"level_3"], inplace=True)

In [53]:
df_final = df_final[df_final['evaluation_status'] != 'Flag']

In [56]:
df_final = df_final[["Original_Sentence", "level_1", "level_2", "level_3", "evaluation_status","issue_details"]]

In [60]:
df_final.head(50)

,Original_Sentence,level_1,level_2,level_3,evaluation_status,issue_details
0,"•• ""عدم الانحياز"" اصطلاح سياسي يعنى الحياد..","""عدم الانحياز"" يعني أن تكون محايداً ولا تفضل أ...","""عدم الانحياز"" هو مصطلح سياسي يعني أن تكون محا...","""عدم الانحياز"" هو مصطلح سياسي يشير إلى الحياد.",Pass,NaN
1,حيث تلتزم الدول غير المنحازة بعدم الارتباط بأي...,الدول غير المنحازة لا تتعامل مع دول الشرق أو ا...,تلتزم الدول غير المنحازة بعدم التحالف مع دول ا...,تلتزم الدول غير المنحازة بالحياد وعدم التحالف ...,Pass,NaN
2,بمعنى أن الدول غير المنحازة لا تقف موقف المتفر...,الدول غير المنحازة ليسوا متفرجين، هم يتدخلون و...,الدول غير المنحازة ليس لها موقف محايد في القضا...,بمعنى أن الدول غير المنحازة ليس موقفها موقف مت...,Moderate,Order Violation
3,وقد بدأ استعمال اصطلاح (عدم الانحياز) في مؤتمر...,"وقد بدأ استخدام مصطلح ""عدم الانحياز"" في مؤتمر ...","وقد بدأ استخدام مصطلح ""عدم الانحياز"" في مؤتمر ...","وقد بدأ استعمال اصطلاح ""عدم الانحياز"" في مؤتمر...",Moderate,Order Violation
5,••السيارات التي يستعملها الدبلوماسيون.. أي رجا...,"السيارات التي يستخدمها الدبلوماسيون تسمى ""هيئة...",تتحمل السيارات التي يستخدمها الدبلوماسيون جملة...,تتحمل السيارات الدبلوماسية، أي تلك التي يستخدم...,Moderate,Order Violation
6,يقصد بالتنمية.. خطة اقتصادية لزيادة الإنتاج.. ...,التنمية هي خطة لتحسين الحياة وزيادة الأشياء ال...,التنمية هي الخطة الاقتصادية التي تهدف إلى زياد...,التنمية هي الخطة الاقتصادية التي تهدف إلى زياد...,Pass,NaN
7,حضرموت – اليمن الديمقراطية,حضرموت - مكان في اليمن.,حضرموت - اليمن,حضرموت - اليمن الفيدرالية.,Pass,NaN
8,العنقاء هي رمز البعث والخلود في الأساطير المصر...,العنقاء رمز الخلود.,العنقاء هي رمز البعث والخلود في الأساطير المصرية.,العنقاء رمز للبعث والخلود في الأساطير المصرية.,Pass,NaN
9,ويقال إنها لما بلغت 500 سنة أحرقت نفسها وبرزت ...,وقيل أنها عندما بلغت 500 سنة أحرقت نفسها وخرج ...,يقال إنها أحرقت نفسها عندما بلغت 500 سنة، وظهر...,ويقال إنها أحرقت نفسها عندما بلغت خمسمائة عام،...,Moderate,Order Violation
10,وقد اعتبرها العرب أحد المستحيلات الثلاثة، العن...,وقد اعتبرها العرب مستحيلة، مثل الطيران مثلًا!,وقد اعتبرها العرب إحدى المستحيلات الثلاث.,وقد اعتبرها العرب إحدى المستحيلات الثلاث.,Moderate,Order Violation
11,عندما قرأنا الخبر صدقنا أن العنقاء موجودة فعلا...,عندما قرأنا الخبر صدمنا لتصديقنا وجود العنقاء ...,صدقنا أن العنقاء موجودة فعلا عند البروفسور وأن...,صدقنا خبر العنقاء عند البروفسور فهي تساوي مليو...,Moderate,Order Violation
13,الأدب الجاهلي هو أدب الفترة التي سبقت ظهور الإ...,الأدب الجاهلي هو أدب الفترة قبل الإسلام.,الأدب الجاهلي هو أدب الفترة التي سبقت ظهور الإ...,الأدب الجاهلي هو أدب الفترة التي سبقت ظهور الإ...,Moderate,Order Violation
14,ردت الصغيرة بقوة: وهل كنت تخافين عندما كنت تعم...,ردت الفتاة بجرأة: هل كنت خائفة عندما قاتلتِ ضد...,ردت الفتاة بجرأة: هل كنت خائفة عندما شاركتِ في...,ردت البنت بجرأة: كيف تجرئين على السؤال! هل كنت...,Moderate,Order Violation
15,فسألته: -ماذا تقرأ؟,فسألته: ماذا تقرأ؟,فسألته: ماذا تقرأ؟,فسألته: ماذا تقرأ؟,Pass,NaN
16,وقال لمن حوله: -أنتم جميعًا مدعوون للغداء عندي...,قال للجميع: دعوتكم لتناول الغداء معي اليوم.,"قال للجميع: ""دعوتكم لتناول الغداء معي اليوم.""","قال للجميع: ""دعوتكم لتناول الغداء معي اليوم"".",Moderate,Order Violation
17,•هل إلقاء السلام على المسلم سنة؟,هل تحية المسلم بأي طريقة هي سنة؟,هل سلام المسلم على أخيه سنة؟,هل سلام المسلم على أخيه سنة؟,Pass,NaN
18,••ابتداء السلام سنة، ورد السلام فرض،,السلام عليكم يعني مرحبا.,ابدأ التحية بالسنة، وأكمل التحية بالتحية.,ابتداء السلام سنة، وورد السلام فرض.,Moderate,"الجملة ""ابتداء السلام سنة، ورد السلام فرض"" صحي..."
22,(سورة القارعة),سورة القارعة.,القارعة.,القارعة.,Pass,NaN
23,أما المقصود بالقارعة التي وردت في بداية هذه ال...,يوم القيامة.,أما المقصود بالقارعة التي وردت في بداية هذه ال...,يوم القيامة.,Moderate,Order Violation
24,قال تعالى: (القارعة) اسم من أسماء يوم القيامة،...,يوم القيامة له أسماء، مثل: القارعة، والحاقة، و...,قال تعالى: القارعة اسم من أسماء يوم القيامة، م...,قال تعالى: القارعة اسم من أسماء يوم القيامة، م...,Moderate,Order Violation
25,بعد أن وصف الله يوم القيامة، قسم الناس فيه إلى...,بعد أن شرح الله يوم القيامة، قسّم الناس إلى قس...,بعد أن وصف الله يوم القيامة، قسم الناس إلى قسم...,بعد أن وصف الله يوم القيامة، قسم الناس فيه إلى...,Pass,NaN
26,أما النبي صلى الله عليه وسلم، فقد كان حريصًا ع...,كان النبي يُصلي بصوتٍ واضحٍ ويفعل نفس الأمر مع...,كان النبي صلى الله عليه وسلم يُجهر بصلاته والق...,كان النبي صلى الله عليه وسلم يُجهر بصلاته والق...,Moderate,Order Violation
27,قالوا في غضب وإصرار: والله لئن مات أبو بكر لنق...,قالوا بغضب: إذا مات أبو بكر، سنقتل عتبة بن ربيعة.,قالوا بغضب: إذا مات أبو بكر سنقتل عتبة بن ربيعة.,قالوا بغضب وإصرار: إذا مات أبو بكر فسوف نقتل ع...,Moderate,Order Violation
28,قالت له: والله مالي علم بصاحبك،,قالت له: أنا ما أعرفش صاحبك.,قالت له: أنا ما أعرف شي عن صاحبك.,قالت له: والله ما أعرف صاحبك.,Moderate,"استخدام ""والله"" في المستوى 3 غير مناسب."
29,ظل النبي صلى الله عليه وسلم ماضيًا في طريقه، ي...,ظل النبي وأصحابه يسيرون في طريقهم، يدعون الناس...,ظل النبي وأصحابه على طريقهم، يدعون الناس إلى ا...,ظل النبي وأصحابه ماضين في طريقهم، ينشرون دعوة ...,Moderate,Order Violation
30,فقد أكد العلماء أن لكل داء دواء في بيئته، وأنه...,كل مرض له دواء، وإذا بحثنا جيداً، يمكننا أن نج...,فقد أكد العلماء أنه يمكن علاج كل مرض ببحث علمي...,فقد أجمع العلماء على أن لكل مرض سبباً في بيئته...,Moderate,Order Violation
31,تتمتع هذه الجزر بنوع من الحكم الذاتي، وأصبح له...,هذه الجزر لديها حكم ذاتي و لديها برلمان محلي.,تتمتع هذه الجزر بنوع من الحكم الذاتي ولديها بر...,تتمتع هذه الجزر بنوع من الحكم الذاتي ولديها بر...,Pass,NaN
32,وهي ذات تكوين بركاني، وترتفع هضابها مباشرة انط...,تضاريسها بركانية، وهضابها ترتفع مباشرة من الشا...,تتميز بتضاريسها الجبلية، وتمتد هضابها من الشاط...,وهي ذات تكوين بركاني، وهضابها ترتفع مباشرة من ...,Moderate,Order Violation
33,وهي معرضة للعديد من الزلازل والثورات البركانية...,تعرضت للكثير من الزلازل والثورات البركانية، مث...,هي معرضة للزلازل والبراكين، مثلما حدث عام 1522...,هي معرضة للزلازل والثورات البركانية، كما حدث ع...,Moderate,Order Violation
34,كما أدت الحمم والصخور البازلتية التي أطلقها أح...,أدى حمم وصخور بازلتية من بركان إلى زيادة مساحة...,أدت الحمم والصخور البازلتية التي أطلقها أحد ال...,أدى تدفق الحمم والصخور البازلتية من أحد البراك...,Moderate,Order Violation
35,وتأسست أول مستوطنة برتغالية في جزيرة (سانتا ما...,تأسست أول مستوطنة برتغالية في جزيرة سانتا ماري...,وتأسست أول مستوطنة برتغالية في جزيرة سانتا مار...,وتأسست أول مستوطنة برتغالية في جزيرة سانتا مار...,Moderate,Order Violation
36,ثم أصبحت، بفضل موقعها الجغرافي الوسيط، نقطة ال...,أصبحت البرتغال قاعدة للسفن القادمة من العالم ا...,أصبحت البرتغال نقطةَ التقاءٍ للسفنِ القادمةِ م...,أصبحت البرتغال نقطةَ التقاءٍ للسفنِ القادمةِ م...,Moderate,Order Violation
37,أبرز صادرات جزر (أزور) المشغولات اليدوية والمط...,تشتهر جزر أزور بمشغولات يدوية ومطرزات وأناناس ...,تشتهر جزر أزور بمشغولات يدوية ومطرزات وأناناس ...,تشتهر جزر أزور بإنتاج المشغولات اليدوية والمطر...,Moderate,Order Violation
38,ولكن معظم الشبان يغادرون موطنهم ويهاجرون إلى أ...,كثير من الشباب يتركون وطنهم ويسافرون إلى أمريك...,يغادر معظم الشباب أوطانهم ويهاجرون إلى أمريكا ...,يغادر معظم الشباب أوطانهم المهجرين إلى أمريكا ...,Pass,NaN
39,تحولت جزر (أزور) إلى قاعدة جوية ومركز اتصالات ...,كانت جزر أزور مركزًا مهمًا للاتصالات والجيوش خ...,جزر أزور أصبحت قاعدة جوية هامة أثناء الحرب الع...,تحوّلت جزر أزور إلى قاعدة جوية ومركز اتصالات ه...,Moderate,Order Violation
40,وكانت لها أهميتها كنقطة للأرصاد الجوية بالنسبة...,كانت هذه النقطة مهمة لمراقبة الطقس في أوروبا ق...,كانت هذه النقطة مهمة للأرصاد الجوية في أوروبا ...,كانت هذه النقطة مهمة للأرصاد الجوية في أوروبا ...,Pass,NaN
41,أكسل الذكور وأكثرهم اعتمادًا على الإناث في مهم...,تضع أنثى طائر التمر الهندي البيض، بينما ذكرها ...,تعتمد الطيور الطنانة الأمريكية الصغيرة وأوزة ا...,تُعد طيور الطنان الأمريكية الصغيرة وأوزة البحر...,Moderate,Order Violation
42,أما المجنيزيوم فقد اكتشفه الصيدلي الفرنسي (أنط...,اكتشف الصيدلي الفرنسي أنطوان بوسي المجنيزيوم س...,اكتشف الصيدلي الفرنسي أنطوان بوسي المجنيزيوم ع...,اكتشف الصيدلي الفرنسي أنطوان بوسي المجنيزيوم ع...,Moderate,Order Violation
43,• تم التوقيع على ميثاق السوق الأوروبية المشترك...,تم توقيع اتفاقية السوق الأوروبية المشتركة في ر...,تم توقيع ميثاق السوق الأوروبية المشتركة في روم...,تمت توقيع اتفاقية السوق الأوروبية المشتركة في ...,Pass,NaN
44,•يحتاج بناء مركبات الفضاء (خصوصًا تلك التي تحم...,يحتاج بناء مركبات الفضاء إلى تركيب الكثير من ا...,يُشترط في بناء مركبات الفضاء، خاصة تلك التي تح...,يحتاج بناء مركبات الفضاء، خاصة تلك التي تحمل ر...,Pass,NaN
45,تعاني (لاجوس) عاصمة نيجريا من مشاكل الازدحام ا...,تعاني لاغوس، عاصمة نيجيريا، من ازدحام شديد ومش...,تعاني لاغوس، عاصمة نيجيريا، من مشاكل الازدحام ...,تعاني لاغوس، عاصمة نيجيريا، من اكتظاظ سكاني وا...,Moderate,Order Violation
46,وقد قررت الحكومة النيجيرية نقل مقرها تدريجيًا ...,قررت الحكومة النيجيرية الانتقال إلى عاصمة جديدة.,قررت الحكومة النيجيرية الانتقال إلى عاصمة جديدة.,قررت الحكومة النيجيرية الانتقال إلى عاصمة جديدة.,Moderate,Order Violation
47,ومن أجل الاطلاع على حضارة الأجانب.. ومعرفة تار...,لمعرفة حضارات أجنبية وتاريخهم وآدابهم وعلومهم.,ومن أجل معرفة ثقافات الشعوب الأخرى، آدابها وتا...,ومن أجل الاطلاع على حضارة الأجانب، وآدابهم، وع...,Moderate,Order Violation
48,اسمها يملأ صفحات التاريخ الإسلامي.. منذ أن كان...,اسمها عرفها التاريخ الإسلامي.. كانت فتاة عاشرت...,اسمها عائشة، وهي أشهر نساء التاريخ الإسلامي.,اسمها يخطف الأنظار في صفحات التاريخ الإسلامي، ...,Moderate,Order Violation
49,وإذا بها تستقبل خبر استشهادهم بقلب الأم المسلم...,وإذا بها أم مسلمة تؤمن تصبر.,استقبلت الأم خبر استشهاد أبنائها بقلب مؤمن صابر.,وإذا بها تستقبل خبر استشهادهم بقلب الأم المسلم...,Moderate,Order Violation
50,هذه هي الخنساء..,هذه هي الخنساء.,هذه هي الخنساء.,هذه هي الخنساء.,Pass,NaN
51,حياتها كلها.. مواقف.. وصور رائعة..,حياتها مليئة بالمواقف والصور الرائعة.,حياتها مليئة بالمواقف والصور الرائعة.,حياتها مليئة بالمواقف والصور الرائعة.,Moderate,Order Violation
52,وقد بدا هذا واضحًا وهم يتحدثون عن آرائهم حول ا...,تحدثوا عن آرائهم حول المؤلفين والرسامين والطبا...,وهم يتحدثون عن آرائهم حول المؤلفين والرسامين و...,وهم يتحدثون عن آرائهم حول المؤلفين والرسامين و...,Moderate,Order Violation
53,وبهذه المناسبة أصدرت هيئة البريد مجموعة من سبع...,صدرت هيئة البريد طوابع تذكارية بمناسبة خاصة، ت...,أصدرت هيئة البريد مجموعة من الطوابع التذكارية ...,صدرت هيئة البريد مجموعة من الطوابع التذكارية ب...,Moderate,بعض الأخطاء في التفاصيل الدقيقة، مثل عدم ذكر أ...
54,وهكذا ساهمت المجلة في تكوين شخصيتي، بعد أن ثبت...,وهكذا ساعدتني المجلة على معرفة نفسي، لأنني كنت...,ساعدتني المجلة على تطوير شخصيتي؛ لأنني كنت ممي...,وهكذا ساهمت المجلة في تشكيل شخصيتي، حيث تميزت ...,Moderate,Order Violation

In [64]:
df_final.to_csv("df_final.csv", index=False)

In [63]:
from IPython.display import FileLink
# Replace 'merged_table.csv' with the actual filename you used
FileLink(df_final)

TypeError: stat: path should be string, bytes, os.PathLike or integer, not DataFrame

In [65]:
import numpy as np

# Split the dataframe into 3 parts
split_list = np.array_split(df_final, 4)

# Save each part
split_list[0].to_csv('merged_part_1.csv', index=False)
split_list[1].to_csv('merged_part_2.csv', index=False)
split_list[2].to_csv('merged_part_3.csv', index=False)
split_list[3].to_csv('merged_part_4.csv', index=False)

print("Split completed successfully. Please download these files individually.")

Split completed successfully. Please download these files individually.

In [57]:
print(f"Success! Total rows: {len(df_final)}")

Success! Total rows: 36723

In [58]:
df_final["evaluation_status"].value_counts()

evaluation_status
Moderate    27461
Pass         9262
Name: count, dtype: int64

In [61]:
df_final.fillna(value="None", inplace=True)

In [62]:
total_nan = df_final.isnull().sum().sum()
print(total_nan)

0

# Hoenstly embarresed by how many tries it took me to figure out I neded to split the file to save it