In [1]:
# Install packages if needed
# Uncomment if running on a fresh environment

# !pip install -q pandas numpy sacrebleu bert-score easse nltk bart-score

In [3]:
import sys, subprocess

def pip_install(pkg):
    try:
        subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", pkg])
        print(f"✅ Installed: {pkg}")
    except subprocess.CalledProcessError:
        print(f"❌ Failed: {pkg}")

packages = [
    "sacrebleu",
    "bert-score",
    "easse",
    "nltk"
]

for pkg in packages:
    pip_install(pkg)

✅ Installed: sacrebleu
✅ Installed: bert-score
✅ Installed: easse
✅ Installed: nltk

In [24]:
!pip install git+https://github.com/feralvam/easse.git

Collecting git+https://github.com/feralvam/easse.git
  Cloning https://github.com/feralvam/easse.git to /tmp/pip-req-build-s2_pmphw
  Running command git clone --filter=blob:none --quiet https://github.com/feralvam/easse.git /tmp/pip-req-build-s2_pmphw
  Resolved https://github.com/feralvam/easse.git to commit 6a4352ec299ed03fda8ee45445ca43d9c7673e89
  Preparing metadata (setup.py) ... done
Collecting tseval@ git+https://github.com/facebookresearch/text-simplification-evaluation.git@main (from easse==0.2.4)
  Cloning https://github.com/facebookresearch/text-simplification-evaluation.git (to revision main) to /tmp/pip-install-_glp0hzn/tseval_d4558ec0484f4c0c9f9176015e6e797f
  Running command git clone --filter=blob:none --quiet https://github.com/facebookresearch/text-simplification-evaluation.git /tmp/pip-install-_glp0hzn/tseval_d4558ec0484f4c0c9f9176015e6e797f
  Resolved https://github.com/facebookresearch/text-simplification-evaluation.git to commit dea8863683ea5946fd50184883c9be7a7339e821
  Preparing metadata (setup.py) ... done
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from easse==0.2.4) (8.3.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from easse==0.2.4) (3.10.0)
Requirement already satisfied: nltk>=3.6.5 in /usr/local/lib/python3.12/dist-packages (from easse==0.2.4) (3.9.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from easse==0.2.4) (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from easse==0.2.4) (2.2.2)
Requirement already satisfied: requests>=2.21.0 in /usr/local/lib/python3.12/dist-packages (from easse==0.2.4) (2.32.4)
Requirement already satisfied: sacrebleu>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from easse==0.2.4) (2.6.0)
Collecting sacremoses (from easse==0.2.4)
  Downloading sacremoses-0.1.1-py3-none-any.whl.metadata (8.3 kB)
Requirement already satisfied: seaborn in /usr/local/lib/python3.12/dist-packages (from easse==0.2.4) (0.13.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from easse==0.2.4) (1.6.1)
Collecting stanfordnlp (from easse==0.2.4)
  Downloading stanfordnlp-0.2.0-py3-none-any.whl.metadata (8.6 kB)
Requirement already satisfied: tqdm>=4.32.2 in /usr/local/lib/python3.12/dist-packages (from easse==0.2.4) (4.67.3)
Collecting yattag (from easse==0.2.4)
  Downloading yattag-1.16.1.tar.gz (29 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: plotly>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from easse==0.2.4) (5.24.1)
Requirement already satisfied: bert_score in /usr/local/lib/python3.12/dist-packages (from easse==0.2.4) (0.3.13)
Collecting simalign (from easse==0.2.4)
  Downloading simalign-0.4-py3-none-any.whl.metadata (6.2 kB)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk>=3.6.5->easse==0.2.4) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk>=3.6.5->easse==0.2.4) (2025.11.3)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly>=4.0.0->easse==0.2.4) (9.1.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from plotly>=4.0.0->easse==0.2.4) (26.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.21.0->easse==0.2.4) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.21.0->easse==0.2.4) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.21.0->easse==0.2.4) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.21.0->easse==0.2.4) (2026.2.25)
Requirement already satisfied: portalocker in /usr/local/lib/python3.12/dist-packages (from sacrebleu>=2.0.0->easse==0.2.4) (3.2.0)
Requirement already satisfied: tabulate>=0.8.9 in /usr/local/lib/python3.12/dist-packages (from sacrebleu>=2.0.0->easse==0.2.4) (0.9.0)
Requirement already satisfied: colorama in /usr/local/lib/python3.12/dist-packages (from sacrebleu>=2.0.0->easse==0.2.4) (0.4.6)
Requirement already satisfied: lxml in /usr/local/lib/python3.12/dist-packages (from sacrebleu>=2.0.0->easse==0.2.4) (6.0.3)
Requirement already satisfied: torch>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from bert_score->easse==0.2.4) (2.10.0+cpu)
Requirement already satisfied: transformers>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from bert_score->easse==0.2.4) (5.0.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->easse==0.2.4) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->easse==0.2.4) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->easse==0.2.4) (2026.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->easse==0.2.4) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->easse==0.2.4) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->easse==0.2.4) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->easse==0.2.4) (1.5.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->easse==0.2.4) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->easse==0.2.4) (3.3.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->easse==0.2.4) (1.16.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->easse==0.2.4) (3.6.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from simalign->easse==0.2.4) (3.6.1)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from stanfordnlp->easse==0.2.4) (5.29.6)
Collecting python-Levenshtein (from tseval@ git+https://github.com/facebookresearch/text-simplification-evaluation.git@main->easse==0.2.4)
  Downloading python_levenshtein-0.27.3-py3-none-any.whl.metadata (3.9 kB)
Requirement already satisfied: gitpython in /usr/local/lib/python3.12/dist-packages (from tseval@ git+https://github.com/facebookresearch/text-simplification-evaluation.git@main->easse==0.2.4) (3.1.46)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->easse==0.2.4) (1.17.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score->easse==0.2.4) (3.25.2)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score->easse==0.2.4) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score->easse==0.2.4) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score->easse==0.2.4) (1.14.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score->easse==0.2.4) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score->easse==0.2.4) (2025.3.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=3.0.0->bert_score->easse==0.2.4) (1.10.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers>=3.0.0->bert_score->easse==0.2.4) (6.0.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=3.0.0->bert_score->easse==0.2.4) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers>=3.0.0->bert_score->easse==0.2.4) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers>=3.0.0->bert_score->easse==0.2.4) (0.7.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython->tseval@ git+https://github.com/facebookresearch/text-simplification-evaluation.git@main->easse==0.2.4) (4.0.12)
Collecting Levenshtein==0.27.3 (from python-Levenshtein->tseval@ git+https://github.com/facebookresearch/text-simplification-evaluation.git@main->easse==0.2.4)
  Downloading levenshtein-0.27.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (3.7 kB)
Collecting rapidfuzz<4.0.0,>=3.9.0 (from Levenshtein==0.27.3->python-Levenshtein->tseval@ git+https://github.com/facebookresearch/text-simplification-evaluation.git@main->easse==0.2.4)
  Downloading rapidfuzz-3.14.5-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (12 kB)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython->tseval@ git+https://github.com/facebookresearch/text-simplification-evaluation.git@main->easse==0.2.4) (5.0.3)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert_score->easse==0.2.4) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert_score->easse==0.2.4) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert_score->easse==0.2.4) (0.24.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.0.0->bert_score->easse==0.2.4) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.0.0->bert_score->easse==0.2.4) (3.0.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert_score->easse==0.2.4) (4.13.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert_score->easse==0.2.4) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert_score->easse==0.2.4) (0.16.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert_score->easse==0.2.4) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert_score->easse==0.2.4) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert_score->easse==0.2.4) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert_score->easse==0.2.4) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert_score->easse==0.2.4) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert_score->easse==0.2.4) (0.1.2)
Downloading sacremoses-0.1.1-py3-none-any.whl (897 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 897.5/897.5 kB 42.6 MB/s eta 0:00:00
Downloading simalign-0.4-py3-none-any.whl (8.1 kB)
Downloading stanfordnlp-0.2.0-py3-none-any.whl (158 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 158.8/158.8 kB 9.4 MB/s eta 0:00:00
Downloading python_levenshtein-0.27.3-py3-none-any.whl (9.5 kB)
Downloading levenshtein-0.27.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (153 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 153.3/153.3 kB 12.0 MB/s eta 0:00:00
Downloading rapidfuzz-3.14.5-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 76.0 MB/s eta 0:00:00
Building wheels for collected packages: easse, tseval, yattag
  Building wheel for easse (setup.py) ... done
  Created wheel for easse: filename=easse-0.2.4-py3-none-any.whl size=5318579 sha256=e7b2c717f73b59c1ae36ae2f05680d6cf9e11c97f0b91b3a108ee2bfe6c5a20e
  Stored in directory: /tmp/pip-ephem-wheel-cache-978ildfy/wheels/67/29/81/aad6b29a88ed353b692f83f801291099a3ee1f5bae0f9fd234
  Building wheel for tseval (setup.py) ... done
  Created wheel for tseval: filename=tseval-1.0-py3-none-any.whl size=8522217 sha256=53d7efc9b6dbd8fd152ecddc0537b810f2985530c7b8d9279db45008c59ddaa5
  Stored in directory: /tmp/pip-ephem-wheel-cache-978ildfy/wheels/fb/f4/10/2ee7ec864f37fd11d8dc94a89c4a3d226023c1938e1cad5aa7
  Building wheel for yattag (setup.py) ... done
  Created wheel for yattag: filename=yattag-1.16.1-py3-none-any.whl size=15886 sha256=57fcd4dcec19294bffa213b7631148151134319461d1ae355ee09a7ae8ee8b1e
  Stored in directory: /root/.cache/pip/wheels/d2/2f/52/049ff4f7c8c9c932b2ece7ec800d7facf2a141ac5ab0ce7e51
Successfully built easse tseval yattag
Installing collected packages: yattag, sacremoses, rapidfuzz, Levenshtein, stanfordnlp, python-Levenshtein, tseval, simalign, easse
Successfully installed Levenshtein-0.27.3 easse-0.2.4 python-Levenshtein-0.27.3 rapidfuzz-3.14.5 sacremoses-0.1.1 simalign-0.4 stanfordnlp-0.2.0 tseval-1.0 yattag-1.16.1

In [9]:
import os
import re
import numpy as np
import pandas as pd
import sacrebleu

from bert_score import score as bert_score_fn
from nltk.translate.meteor_score import meteor_score
import nltk

nltk.download("wordnet", quiet=True)
nltk.download("omw-1.4", quiet=True)

# Try importing corpus_sari from easse first, then fall back to a simple implementation if unavailable
try:
    from easse.sari import corpus_sari
    HAS_EASSE = True
except Exception:
    HAS_EASSE = False
    print("easse not found. Install with: !pip install easse")
    corpus_sari = None

# BARTScore
try:
    import torch
    from bart_score import BARTScorer
    HAS_BARTSCORE = True
except Exception:
    HAS_BARTSCORE = False
    print("bart-score not found. Install with: !pip install bart-score")

bart-score not found. Install with: !pip install bart-score

## 1) Configure paths and column names

Edit only this cell.

In [1]:
# ===== File path =====
CSV_PATH = "/kaggle/input/datasets/naghamabdullahalshab/samples/final_df_with_lexical_simplifications.csv"  

# ===== Core columns in your CSV =====
COL_ORIGINAL = "Original_Sentence"
COL_REF1 = "level_1"
COL_REF2 = "level_2"
COL_REF3 = "level_3"
COL_LEXICAL = "lexical_simplified_text"

# ===== Optional hybrid prediction columns =====
# If your CSV already has hybrid outputs, put their names here.
# If they do not exist, leave them as None and the notebook will skip hybrid evaluation.
COL_HYBRID_L1 = None   # e.g. "hybrid_l1"
COL_HYBRID_L2 = None   # e.g. "hybrid_l2"
COL_HYBRID_L3 = None   # e.g. "hybrid_l3"

# ===== Runtime options =====
RUN_BERTSCORE = True
RUN_BARTSCORE = True
DEVICE = "cuda"  # or "cpu"

In [2]:
import pandas as pd

encodings = ["utf-8-sig", "utf-16", "utf-16le", "utf-16be", "cp1256", "windows-1256"]

for enc in encodings:
    try:
        df_test = pd.read_csv(CSV_PATH, encoding=enc, engine="python", nrows=5)
        print("✅ Encoding works:", enc)
        display(df_test.head())
        break
    except Exception as e:
        print("❌ Failed:", enc, "|", type(e).__name__, str(e)[:100])

✅ Encoding works: utf-8-sig

,Original_Sentence,level_1,level_2,level_3,evaluation_status,issue_details,cwi_details,complex_words,mlm_substitutions,filtered_substitutions,final_substitutions,lexical_simplified_text,replacement_map
0,"•• ""عدم الانحياز"" اصطلاح سياسي يعنى الحياد..","""عدم الانحياز"" يعني أن تكون محايداً ولا تفضل أ...","""عدم الانحياز"" هو مصطلح سياسي يعني أن تكون محا...","""عدم الانحياز"" هو مصطلح سياسي يشير إلى الحياد.",Pass,NaN,"[{'token': 'عدم', 'lemma': 'عَدَم', 'pos': 'no...","['الانحياز', 'اصطلاح', 'سياسي', 'الحياد']","[{'original_sentence': '•• ""عدم الانحياز"" اصطل...","[{'complex_word': 'الانحياز', 'target_pos': 'n...","[{'complex_word': 'الانحياز', 'replacement': '...","•• ""عدم الرضا"" مصطلح عربي يعنى الاستقلال..","['الانحياز -> الرضا', 'اصطلاح -> مصطلح', 'سياس..."
1,حيث تلتزم الدول غير المنحازة بعدم الارتباط بأي...,الدول غير المنحازة لا تتعامل مع دول الشرق أو ا...,تلتزم الدول غير المنحازة بعدم التحالف مع دول ا...,تلتزم الدول غير المنحازة بالحياد وعدم التحالف ...,Pass,NaN,"[{'token': 'حيث', 'lemma': 'حَيْثُ', 'pos': 'c...",['المنحازة'],[{'original_sentence': 'حيث تلتزم الدول غير ال...,"[{'complex_word': 'المنحازة', 'target_pos': 'n...",[],حيث تلتزم الدول غير المنحازة بعدم الارتباط بأي...,[]
2,بمعنى أن الدول غير المنحازة لا تقف موقف المتفر...,الدول غير المنحازة ليسوا متفرجين، هم يتدخلون و...,الدول غير المنحازة ليس لها موقف محايد في القضا...,بمعنى أن الدول غير المنحازة ليس موقفها موقف مت...,Moderate,Order Violation,"[{'token': 'بمعنى', 'lemma': 'مَعْنَى', 'pos':...","['المنحازة', 'المتفرج', 'العالمية']",[{'original_sentence': 'بمعنى أن الدول غير الم...,"[{'complex_word': 'المنحازة', 'target_pos': 'n...","[{'complex_word': 'المنحازة', 'replacement': '...",بمعنى أن الدول غير العظمى لا تقف موقف واحد أما...,"['المنحازة -> العظمى', 'المتفرج -> واحد', 'الع..."
3,وقد بدأ استعمال اصطلاح (عدم الانحياز) في مؤتمر...,"وقد بدأ استخدام مصطلح ""عدم الانحياز"" في مؤتمر ...","وقد بدأ استخدام مصطلح ""عدم الانحياز"" في مؤتمر ...","وقد بدأ استعمال اصطلاح ""عدم الانحياز"" في مؤتمر...",Moderate,Order Violation,"[{'token': 'وقد', 'lemma': 'قَدْ', 'pos': 'par...","['اصطلاح', 'الانحياز', '،', 'منحازة']",[{'original_sentence': 'وقد بدأ استعمال اصطلاح...,"[{'complex_word': 'اصطلاح', 'target_pos': 'nou...","[{'complex_word': 'اصطلاح', 'replacement': 'مص...",وقد بدأ استعمال مصطلح (عدم الاستقلال) في مؤتمر...,"['اصطلاح -> مصطلح', 'الانحياز -> الاستقلال', '..."
4,••السيارات التي يستعملها الدبلوماسيون.. أي رجا...,"السيارات التي يستخدمها الدبلوماسيون تسمى ""هيئة...",تتحمل السيارات التي يستخدمها الدبلوماسيون جملة...,تتحمل السيارات الدبلوماسية، أي تلك التي يستخدم...,Moderate,Order Violation,"[{'token': 'السيارات', 'lemma': 'سَيّارَة', 'p...",['سياسية'],[{'original_sentence': '••السيارات التي يستعمل...,"[{'complex_word': 'سياسية', 'target_pos': 'adj...","[{'complex_word': 'سياسية', 'replacement': 'ال...",••السيارات التي يستعملها الدبلوماسيون.. أي رجا...,['سياسية -> الدبلوماسية']

In [3]:
import pandas as pd
import csv
import sys

csv.field_size_limit(sys.maxsize)

df = pd.read_csv(
    CSV_PATH,
    encoding="utf-8-sig",
    engine="python",
    on_bad_lines="skip"
)

print("Shape:", df.shape)
print("Columns:", list(df.columns))
display(df.head())

Shape: (34294, 13)
Columns: ['Original_Sentence', 'level_1', 'level_2', 'level_3', 'evaluation_status', 'issue_details', 'cwi_details', 'complex_words', 'mlm_substitutions', 'filtered_substitutions', 'final_substitutions', 'lexical_simplified_text', 'replacement_map']

,Original_Sentence,level_1,level_2,level_3,evaluation_status,issue_details,cwi_details,complex_words,mlm_substitutions,filtered_substitutions,final_substitutions,lexical_simplified_text,replacement_map
0,"•• ""عدم الانحياز"" اصطلاح سياسي يعنى الحياد..","""عدم الانحياز"" يعني أن تكون محايداً ولا تفضل أ...","""عدم الانحياز"" هو مصطلح سياسي يعني أن تكون محا...","""عدم الانحياز"" هو مصطلح سياسي يشير إلى الحياد.",Pass,NaN,"[{'token': 'عدم', 'lemma': 'عَدَم', 'pos': 'no...","['الانحياز', 'اصطلاح', 'سياسي', 'الحياد']","[{'original_sentence': '•• ""عدم الانحياز"" اصطل...","[{'complex_word': 'الانحياز', 'target_pos': 'n...","[{'complex_word': 'الانحياز', 'replacement': '...","•• ""عدم الرضا"" مصطلح عربي يعنى الاستقلال..","['الانحياز -> الرضا', 'اصطلاح -> مصطلح', 'سياس..."
1,حيث تلتزم الدول غير المنحازة بعدم الارتباط بأي...,الدول غير المنحازة لا تتعامل مع دول الشرق أو ا...,تلتزم الدول غير المنحازة بعدم التحالف مع دول ا...,تلتزم الدول غير المنحازة بالحياد وعدم التحالف ...,Pass,NaN,"[{'token': 'حيث', 'lemma': 'حَيْثُ', 'pos': 'c...",['المنحازة'],[{'original_sentence': 'حيث تلتزم الدول غير ال...,"[{'complex_word': 'المنحازة', 'target_pos': 'n...",[],حيث تلتزم الدول غير المنحازة بعدم الارتباط بأي...,[]
2,بمعنى أن الدول غير المنحازة لا تقف موقف المتفر...,الدول غير المنحازة ليسوا متفرجين، هم يتدخلون و...,الدول غير المنحازة ليس لها موقف محايد في القضا...,بمعنى أن الدول غير المنحازة ليس موقفها موقف مت...,Moderate,Order Violation,"[{'token': 'بمعنى', 'lemma': 'مَعْنَى', 'pos':...","['المنحازة', 'المتفرج', 'العالمية']",[{'original_sentence': 'بمعنى أن الدول غير الم...,"[{'complex_word': 'المنحازة', 'target_pos': 'n...","[{'complex_word': 'المنحازة', 'replacement': '...",بمعنى أن الدول غير العظمى لا تقف موقف واحد أما...,"['المنحازة -> العظمى', 'المتفرج -> واحد', 'الع..."
3,وقد بدأ استعمال اصطلاح (عدم الانحياز) في مؤتمر...,"وقد بدأ استخدام مصطلح ""عدم الانحياز"" في مؤتمر ...","وقد بدأ استخدام مصطلح ""عدم الانحياز"" في مؤتمر ...","وقد بدأ استعمال اصطلاح ""عدم الانحياز"" في مؤتمر...",Moderate,Order Violation,"[{'token': 'وقد', 'lemma': 'قَدْ', 'pos': 'par...","['اصطلاح', 'الانحياز', '،', 'منحازة']",[{'original_sentence': 'وقد بدأ استعمال اصطلاح...,"[{'complex_word': 'اصطلاح', 'target_pos': 'nou...","[{'complex_word': 'اصطلاح', 'replacement': 'مص...",وقد بدأ استعمال مصطلح (عدم الاستقلال) في مؤتمر...,"['اصطلاح -> مصطلح', 'الانحياز -> الاستقلال', '..."
4,••السيارات التي يستعملها الدبلوماسيون.. أي رجا...,"السيارات التي يستخدمها الدبلوماسيون تسمى ""هيئة...",تتحمل السيارات التي يستخدمها الدبلوماسيون جملة...,تتحمل السيارات الدبلوماسية، أي تلك التي يستخدم...,Moderate,Order Violation,"[{'token': 'السيارات', 'lemma': 'سَيّارَة', 'p...",['سياسية'],[{'original_sentence': '••السيارات التي يستعمل...,"[{'complex_word': 'سياسية', 'target_pos': 'adj...","[{'complex_word': 'سياسية', 'replacement': 'ال...",••السيارات التي يستعملها الدبلوماسيون.. أي رجا...,['سياسية -> الدبلوماسية']

## 2) Clean rows and normalize text

In [4]:
import re

def normalize_unicode(text):
    if pd.isna(text):
        return ""
    text = str(text)
    text = text.replace("أ", "ا").replace("إ", "ا").replace("آ", "ا").replace("ٱ", "ا")
    text = text.replace("ى", "ي").replace("ؤ", "و").replace("ئ", "ي")
    text = re.sub(r"[\u064B-\u065F\u0670\u0617-\u061A\u06D6-\u06ED]", "", text)  # remove diacritics
    text = re.sub(r"\s+", " ", text).strip()
    return text

def clean_text_col(series):
    return series.fillna("").astype(str).map(normalize_unicode)

needed_cols = [COL_ORIGINAL, COL_REF1, COL_REF2, COL_REF3, COL_LEXICAL]
present_needed = [c for c in needed_cols if c is not None]

df = df.dropna(subset=present_needed).copy()

for col in [COL_ORIGINAL, COL_REF1, COL_REF2, COL_REF3, COL_LEXICAL]:
    df[col] = clean_text_col(df[col])

for col in [COL_HYBRID_L1, COL_HYBRID_L2, COL_HYBRID_L3]:
    if col is not None and col in df.columns:
        df[col] = clean_text_col(df[col])

print("Usable rows:", len(df))
df[[COL_ORIGINAL, COL_REF1, COL_REF2, COL_REF3, COL_LEXICAL]].head()

Usable rows: 34294

,Original_Sentence,level_1,level_2,level_3,lexical_simplified_text
0,"•• ""عدم الانحياز"" اصطلاح سياسي يعني الحياد..","""عدم الانحياز"" يعني ان تكون محايدا ولا تفضل احدا.","""عدم الانحياز"" هو مصطلح سياسي يعني ان تكون محا...","""عدم الانحياز"" هو مصطلح سياسي يشير الي الحياد.","•• ""عدم الرضا"" مصطلح عربي يعني الاستقلال.."
1,حيث تلتزم الدول غير المنحازة بعدم الارتباط باي...,الدول غير المنحازة لا تتعامل مع دول الشرق او ا...,تلتزم الدول غير المنحازة بعدم التحالف مع دول ا...,تلتزم الدول غير المنحازة بالحياد وعدم التحالف ...,حيث تلتزم الدول غير المنحازة بعدم الارتباط باي...
2,بمعني ان الدول غير المنحازة لا تقف موقف المتفر...,الدول غير المنحازة ليسوا متفرجين، هم يتدخلون و...,الدول غير المنحازة ليس لها موقف محايد في القضا...,بمعني ان الدول غير المنحازة ليس موقفها موقف مت...,بمعني ان الدول غير العظمي لا تقف موقف واحد اما...
3,وقد بدا استعمال اصطلاح (عدم الانحياز) في موتمر...,"وقد بدا استخدام مصطلح ""عدم الانحياز"" في موتمر ...","وقد بدا استخدام مصطلح ""عدم الانحياز"" في موتمر ...","وقد بدا استعمال اصطلاح ""عدم الانحياز"" في موتمر...",وقد بدا استعمال مصطلح (عدم الاستقلال) في موتمر...
4,••السيارات التي يستعملها الدبلوماسيون.. اي رجا...,"السيارات التي يستخدمها الدبلوماسيون تسمي ""هيية...",تتحمل السيارات التي يستخدمها الدبلوماسيون جملة...,تتحمل السيارات الدبلوماسية، اي تلك التي يستخدم...,••السيارات التي يستعملها الدبلوماسيون.. اي رجا...

In [19]:
!pip install -q textstat

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 177.1/177.1 kB 5.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 21.4 MB/s eta 0:00:00

## 4) Metric helpers

In [7]:
def osman_score(hypothesis, reference):
    """
    OSMAN approximation:
    Arabic-normalized METEOR average x 100.
    """
    scores = []
    for hyp, ref in zip(hypothesis, reference):
        hyp_norm = normalize_unicode(hyp)
        ref_norm = normalize_unicode(ref)
        hyp_tokens = hyp_norm.split()
        ref_tokens = ref_norm.split()
        if not hyp_tokens or not ref_tokens:
            scores.append(0.0)
            continue
        score = meteor_score([ref_tokens], hyp_tokens)
        scores.append(score)
    return float(np.mean(scores)) * 100

def safe_corpus_sari(orig_sents, sys_sents, refs_sents):
    if corpus_sari is None:
        raise ImportError("SARI requires easse. Please run: !pip install easse")
    return corpus_sari(
        orig_sents=orig_sents,
        sys_sents=sys_sents,
        refs_sents=refs_sents,
    )

def evaluate_predictions(sources, predictions, references, label, compute_sari=False):
    """
    Evaluate a list of predictions against one reference list.
    """
    print(f"\n{'='*70}")
    print(label)
    print(f"{'='*70}")

    result = {"label": label, "n": len(predictions)}

    if compute_sari:
        sari = safe_corpus_sari(
            orig_sents=sources,
            sys_sents=predictions,
            refs_sents=[references],
        )
        print(f"SARI        : {sari:.2f}")
        result["sari"] = sari

    bleu_score = sacrebleu.corpus_bleu(predictions, [references]).score
    print(f"BLEU        : {bleu_score:.2f}")
    result["bleu"] = bleu_score

    if RUN_BERTSCORE:
        P, R, F1 = bert_score_fn(
            predictions,
            references,
            lang="ar",
            verbose=False,
        )
        bs = F1.mean().item()
        print(f"BERTScore F1: {bs:.4f}")
        result["bertscore_f1"] = bs

    if RUN_BARTSCORE:
        bart_scores = bart_scorer.score(predictions, references, batch_size=8)
        bart_avg = float(np.mean(bart_scores))
        print(f"BARTScore   : {bart_avg:.4f}")
        result["bartscore"] = bart_avg

    osman = osman_score(predictions, references)
    print(f"OSMAN       : {osman:.2f}")
    result["osman"] = osman

    return result

## 5) Build lists from CSV

In [15]:
sources = df[COL_ORIGINAL].tolist()

ref1 = df[COL_REF1].tolist()
ref2 = df[COL_REF2].tolist()
ref3 = df[COL_REF3].tolist()

lexical_output = df[COL_LEXICAL].tolist()

hybrid_l1 = df[COL_HYBRID_L1].tolist() if (COL_HYBRID_L1 is not None and COL_HYBRID_L1 in df.columns) else None
hybrid_l2 = df[COL_HYBRID_L2].tolist() if (COL_HYBRID_L2 is not None and COL_HYBRID_L2 in df.columns) else None
hybrid_l3 = df[COL_HYBRID_L3].tolist() if (COL_HYBRID_L3 is not None and COL_HYBRID_L3 in df.columns) else None

print("Rows:", len(sources))

Rows: 34294

## 6) Compute the requested lexical SARI scores

Requested:
- `SARI(original, lexical_output, [ref1])`
- `SARI(original, lexical_output, [ref2])`
- `SARI(original, lexical_output, [ref3])`

This cell also computes BLEU, BERTScore, BARTScore, and OSMAN for the same lexical output vs each reference.

In [17]:
RUN_BERTSCORE = False
RUN_BARTSCORE = False

In [18]:
all_results = []

for refs, label in [
    (ref1, "Lexical output vs Ref 1"),
    (ref2, "Lexical output vs Ref 2"),
    (ref3, "Lexical output vs Ref 3"),
]:
    res = evaluate_predictions(
        sources=sources,
        predictions=lexical_output,
        references=refs,
        label=label,
        compute_sari=True,
    )
    all_results.append(res)

lexical_results_df = pd.DataFrame(all_results)
lexical_results_df

======================================================================
Lexical output vs Ref 1
======================================================================
SARI        : 17.40

WARNING:sacrebleu:That's 100 lines that end in a tokenized period ('.')
WARNING:sacrebleu:It looks like you forgot to detokenize your test data, which may hurt your score.
WARNING:sacrebleu:If you insist your data is detokenized, or don't care, you can suppress this message with the `force` parameter.

BLEU        : 7.93
OSMAN       : 26.09

======================================================================
Lexical output vs Ref 2
======================================================================
SARI        : 22.59

WARNING:sacrebleu:That's 100 lines that end in a tokenized period ('.')
WARNING:sacrebleu:It looks like you forgot to detokenize your test data, which may hurt your score.
WARNING:sacrebleu:If you insist your data is detokenized, or don't care, you can suppress this message with the `force` parameter.

BLEU        : 18.34
OSMAN       : 39.55

======================================================================
Lexical output vs Ref 3
======================================================================
SARI        : 24.81

WARNING:sacrebleu:That's 100 lines that end in a tokenized period ('.')
WARNING:sacrebleu:It looks like you forgot to detokenize your test data, which may hurt your score.
WARNING:sacrebleu:If you insist your data is detokenized, or don't care, you can suppress this message with the `force` parameter.

BLEU        : 23.78
OSMAN       : 47.17

                     label      n       sari       bleu      osman
0  Lexical output vs Ref 1  34294  17.399099   7.934071  26.086146
1  Lexical output vs Ref 2  34294  22.592245  18.343522  39.554145
2  Lexical output vs Ref 3  34294  24.814693  23.780851  47.170764

In [9]:
!pip install bert-score

Collecting bert-score
  Downloading bert_score-0.3.13-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: torch>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from bert-score) (2.10.0+cpu)
Requirement already satisfied: pandas>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from bert-score) (2.3.3)
Requirement already satisfied: transformers>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from bert-score) (5.0.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from bert-score) (2.0.2)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from bert-score) (2.32.4)
Requirement already satisfied: tqdm>=4.31.1 in /usr/local/lib/python3.12/dist-packages (from bert-score) (4.67.3)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from bert-score) (3.10.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from bert-score) (26.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.1->bert-score) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.1->bert-score) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.1->bert-score) (2025.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (3.24.3)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (2026.2.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=3.0.0->bert-score) (1.4.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers>=3.0.0->bert-score) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers>=3.0.0->bert-score) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=3.0.0->bert-score) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers>=3.0.0->bert-score) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers>=3.0.0->bert-score) (0.7.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert-score) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert-score) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert-score) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert-score) (1.4.9)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert-score) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert-score) (3.3.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->bert-score) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->bert-score) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->bert-score) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->bert-score) (2026.1.4)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert-score) (1.3.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert-score) (0.28.1)
Requirement already satisfied: shellingham in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert-score) (1.5.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.1->bert-score) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.0.0->bert-score) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.0.0->bert-score) (3.0.3)
Requirement already satisfied: typer>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from typer-slim->transformers>=3.0.0->bert-score) (0.24.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert-score) (4.12.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert-score) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert-score) (0.16.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim->transformers>=3.0.0->bert-score) (8.3.1)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim->transformers>=3.0.0->bert-score) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim->transformers>=3.0.0->bert-score) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim->transformers>=3.0.0->bert-score) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim->transformers>=3.0.0->bert-score) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer>=0.24.0->typer-slim->transformers>=3.0.0->bert-score) (0.1.2)
Downloading bert_score-0.3.13-py3-none-any.whl (61 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.1/61.1 kB 1.7 MB/s eta 0:00:00
Installing collected packages: bert-score
Successfully installed bert-score-0.3.13

In [10]:
from bert_score import score as bert_score_fn
import pandas as pd

COL_LEXICAL = "lexical_simplified_text"

refs = {
    "Ref Level 1": "level_1",
    "Ref Level 2": "level_2",
    "Ref Level 3": "level_3"
}

all_results = []

for label, ref_col in refs.items():
    P, R, F1 = bert_score_fn(
        cands=df[COL_LEXICAL].fillna("").astype(str).tolist(),
        refs=df[ref_col].fillna("").astype(str).tolist(),
        lang="ar",
        verbose=True
    )

    all_results.append({
        "Comparison": f"Lexical vs {label}",
        "BERTScore_P": P.mean().item(),
        "BERTScore_R": R.mean().item(),
        "BERTScore_F1": F1.mean().item()
    })

bert_results_df = pd.DataFrame(all_results)
bert_results_df

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/625 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/714M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: bert-base-multilingual-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

calculating scores...
computing bert embedding.

  0%|          | 0/1071 [00:00<?, ?it/s]

computing greedy matching.

  0%|          | 0/536 [00:00<?, ?it/s]

done in 4185.12 seconds, 8.19 sentences/sec

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: bert-base-multilingual-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

calculating scores...
computing bert embedding.

  0%|          | 0/1071 [00:00<?, ?it/s]

computing greedy matching.

  0%|          | 0/536 [00:00<?, ?it/s]

done in 4217.02 seconds, 8.13 sentences/sec

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: bert-base-multilingual-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

calculating scores...
computing bert embedding.

  0%|          | 0/1070 [00:00<?, ?it/s]

computing greedy matching.

  0%|          | 0/536 [00:00<?, ?it/s]

done in 4249.12 seconds, 8.07 sentences/sec

               Comparison  BERTScore_P  BERTScore_R  BERTScore_F1
0  Lexical vs Ref Level 1     0.765473     0.802212      0.782685
1  Lexical vs Ref Level 2     0.813176     0.837670      0.824568
2  Lexical vs Ref Level 3     0.837453     0.858588      0.847264

In [13]:
import pandas as pd
from IPython.display import FileLink, display

final_scores_df = pd.DataFrame([
    {
        "label": "Lexical output vs Ref 1",
        "n": 34294,
        "SARI": 17.399099,
        "BLEU": 7.934071,
        "OSMAN_reference_based": 26.086146,
        "BERTScore_P": 0.765473,
        "BERTScore_R": 0.802212,
        "BERTScore_F1": 0.782685,
        "Average_OSMAN_readability": 88.89052716161507
    },
    {
        "label": "Lexical output vs Ref 2",
        "n": 34294,
        "SARI": 22.592245,
        "BLEU": 18.343522,
        "OSMAN_reference_based": 39.554145,
        "BERTScore_P": 0.813176,
        "BERTScore_R": 0.837670,
        "BERTScore_F1": 0.824568,
        "Average_OSMAN_readability": 88.89052716161507
    },
    {
        "label": "Lexical output vs Ref 3",
        "n": 34294,
        "SARI": 24.814693,
        "BLEU": 23.780851,
        "OSMAN_reference_based": 47.170764,
        "BERTScore_P": 0.837453,
        "BERTScore_R": 0.858588,
        "BERTScore_F1": 0.847264,
        "Average_OSMAN_readability": 88.89052716161507
    }
])

output_path = "/kaggle/working/lexical_final_scores_summary.csv"
final_scores_df.to_csv(output_path, index=False)

print(final_scores_df)
display(FileLink(output_path))

                     label      n       SARI       BLEU  \
0  Lexical output vs Ref 1  34294  17.399099   7.934071
1  Lexical output vs Ref 2  34294  22.592245  18.343522
2  Lexical output vs Ref 3  34294  24.814693  23.780851

   OSMAN_reference_based  BERTScore_P  BERTScore_R  BERTScore_F1  \
0              26.086146     0.765473     0.802212      0.782685
1              39.554145     0.813176     0.837670      0.824568
2              47.170764     0.837453     0.858588      0.847264

   Average_OSMAN_readability
0                  88.890527
1                  88.890527
2                  88.890527

/kaggle/working/lexical_final_scores_summary.csv